### ISSUE TITLE
[Investigate] Look at implementing Austin Davies approach to achieve SSR Auth

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#101]
Investigate if @AustinDavies approach from [this medium article](https://levelup.gitconnected.com/using-firebase-authentication-in-a-nuxt-server-side-rendered-application-c2a624a9e999) would be worth implementing, either in addition to or to replace the [current service-worker approach](https://firebase.nuxtjs.org/tutorials/ssr/) for authenticating a user with Firebase Auth on SSR.

**Comment by AustinDavies** [comment]
> Investigate if @AustinDavies approach from [this medium article](https://levelup.gitconnected.com/using-firebase-authentication-in-a-nuxt-server-side-rendered-application-c2a624a9e999) would be worth implementing, either in addition to or to replace the [current service-worker approach](https://firebase.nuxtjs.org/tutorials/ssr/) for authenticating a user with Firebase Auth on SSR.

The approach in that article may be a good fallback option for the service worker approach like you said. However, the service worker approach offers, by far, the best experience for the user. 

The idea in that article is the user shall only be disconnected from their session for the one hour allocated to the auth token via Google Auth. Upon returning to the site after an hour, the server will force the user to log back in. Ideally, you wouldn't want to do that and prefer to just update the current user token.

So what is concerning about the service worker to me is that I know of at least one other Nuxt module that uses a service worker and that is the [Nuxt/PWA](https://pwa.nuxtjs.org/modules/workbox.html#swtemplate) module. This too works off the fetch event but for caching assets/requests. Nevertheless, It too creates/copies a service worker to the static directory by default thus causing conflict.

I would be interested in figuring out the best way to sort of merge or chain any service worker fetch logic together from any potential module needing to leverage that particular service worker event. I may investigate this a bit too in my free time, however, my free time is very limited as of now.

**Comment by lupas** [comment]
> The approach in that article may be a good fallback option for the service worker approach like you said. However, the service worker approach offers, by far, the best experience for the user.

Which makes it worth considering adding :)

> So what is concerning about the service worker to me is that I know of at least one other Nuxt module that uses a service worker and that is the [Nuxt/PWA](https://pwa.nuxtjs.org/modules/workbox.html#swtemplate) module. This too works off the fetch event but for caching assets/requests. Nevertheless, It too creates/copies a service worker to the static directory by default thus causing conflict.
> 
> I would be interested in figuring out the best way to sort of merge or chain any service worker fetch logic together from any potential module needing to leverage that particular service worker event. I may investigate this a bit too in my free time, however, my free time is very limited as of now.

@AustinDavies 
That is one of the flaws my implementation has at this point, but there should be an easy solution to that.

I see different options:

- Option to configure the service-worker's filename so and NOT load it, and expect the user to load it him/herself (e.g. by creating one's own `sw.js` file and using **importScripts()** as mentioned [here](https://medium.com/tengio-ltd/merging-multiple-service-worker-scripts-in-the-same-scope-83213da915ad).

- Add an option for people to add their other sw-files, and we load them for them, as the PWA module seems to do with their [swURL option](https://pwa.nuxtjs.org/modules/workbox.html#swurl) to register further service workers

I guess first option would be the better choice. Will also have to look more into it.

**Comment by lupas** [comment]
@AustinDavies 
Since v5 we go around the service-worker issue by advising using `nuxtjs/pwa` module to import the script additionally. Of course, if a user has other service-workers, or prefers to load in another way, that is always an option, too.
