### ISSUE TITLE
Create demo

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt-community/firebase-module#108]
- [ ] Create demo from https://github.com/lupas/nuxt-fire-demo

- [ ] Consider creating a demo for SPA mode

**Comment by thebspin** [comment]
Could there also plz be a SPA demo and not only universal?
I like to see how to do authentication on refresh for example.

**Comment by lupas** [comment]
> Could there also plz be a SPA demo and not only universal?
> I like to see how to do authentication on refresh for example.

Thanks for the input @thebspin , will consider adding a small demo for that, too.

Authentication for SPA is quite straightforward. If you have any concrete issues with that just hit me up on nuxt discord channel :)

**Comment by bitbytebit1** [comment]
Are there any special requirements to use this module in a static website configuration? I'm trying to use it with Netlify.

**Comment by rajesh-h** [comment]
@thebspin were you able to come up with something for SPA?

**Comment by bozobit** [comment]
Yes, it would help me greatly to see a simple nuxt SPA app pattern that has a registration and login form where the user registers or logs in and the app shows either that the user is logged (with email address).  Having it also write a users collection in Firestore would be good.  There would also be a logout and a timeout logout using local persistence.  That's a really typical use case, and it would really help me get started (and many others).

**Comment by lupas** [comment]
@bozobit 
I'll think of making some example projects for the most common use cases, I'll let you know when I got something :)

**Comment by lupas** [comment]
Tracking tutorials / guides for auth in https://github.com/nuxt-community/firebase-module/issues/380, demo will keep at https://github.com/lupas/nuxt-firebase-demo/blob/master/components/examples/Messaging.vue for now to not make this repo too big, closing this issue for now.
