### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt-community/firebase-module#109]

**Comment by lupas** [comment]
One important test we need:
- Check if module still works when services are not set in nuxt.config.js, e.g.:
```js
// this should work
 services: {
        firestore: true,
        auth: false
}
// this should ALSO work
 services: {
        firestore: true,
        // auth: false
}
```
e.g just happened in regression bug https://github.com/nuxt-community/firebase-module/pull/124

**Comment by lupas** [comment]
Big chunk of this will be done with https://github.com/nuxt-community/firebase-module/pull/258

**Comment by lupas** [comment]
Various tests added in dev with v7.0.0 (released soon)
