### ISSUE TITLE
authentication guards in middle ware on application load

### ISSUE THREAD

**Issue by timdiacon** [nuxt-community/firebase-module#111]
I'm looking to implement authentication guards on some routes in the same way raised in #28 

My problem is the currentUser object is always null on the first page load. The middle ware works perfectly on subsequent pages but it seems the currentUser object isn't initialised in time to be there for the first page load.

If a user loads /user/profile I want to redirect them to /user/login if they are not logged but can't see a way to do this in the middleware on that first page load.

**Comment by timdiacon** [comment]
I think I've answered my own question.

If you use the "onSuccessMutation" option in the nuxt.config to set an authenticated variable in your store then you can check this in the middleware and it return the expected value.

`middleware({ store, redirect }) {
  if(!store.state.authenticated){
    redirect('/user/login')
	},`

**Comment by kpguru20001** [comment]
Hi this method did not work is there any other way
