### ISSUE TITLE
Read Firebase API keys from .env

### ISSUE THREAD

**Issue by kwatog** [nuxt-community/firebase-module#113]
I'm sure this has been discussed before but I can't seem to find the thread. Anyway, I'm trying to set the config from process.env inside nuxt.config.js but the value seems to be empty. 

Is there another way to do this, say via plugin?

  ```
firebase: {
    config: {
      apiKey: process.env.apiKey,
      authDomain: process.env.authDomain,
      databaseURL: process.env.databaseURL,
      projectId: process.env.projectId,
      storageBucket: process.env.storageBucket,
      messagingSenderId: process.env.messagingSenderId,
      appId: process.env.appId,
      measurementId: process.env.measurementId
    },
    services: {
      auth: true  
    }  
}
```

**Comment by kwatog** [comment]
apologies, noob mistake.
I forgot to add `require('dotenv').config()` at the top of the nuxt.config.js

**Comment by obsessen** [comment]
Hello @kwatog, I'm trying to move my config information to the .env file as well but if I do firebase stops working - it just sends one request after another which all have a 200 response but fail. I do have the require statement at the top of nuxt.config.js and other .env variables work without a problem. 

Is there a better way to securely store the firebase credentials?

**Comment by kwatog** [comment]
am not really sure but you can checkout the nuxt config of the boilerplate that I'm doing.

https://github.com/kwatog/manbok/tree/master/nuxt.config.js

**Comment by Mctony17** [comment]
> apologies, noob mistake.
> I forgot to add `require('dotenv').config()` at the top of the nuxt.config.js

Please can we have the entire snippet on how you solved it? I'm stuck here trying to solve same problem.
Thanks.

**Comment by kwatog** [comment]
here's the link to my [nuxt.config.js](https://github.com/kwatog/manbok/blob/master/nuxt.config.js) 

take note that the env file should be named ".env" as dotenv only reads that filename. it won't accept any other filename.

and then you need to make sure to load env before the export block

```
require('dotenv').config()
export default {
```

**Comment by Mctony17** [comment]
Thanks Mike for responding and swiftly too, I'll look at it now.
