### ISSUE TITLE
connect to cloud firestore emulator 

### ISSUE THREAD

**Issue by suryaiiit** [nuxt-community/firebase-module#115]
Hey,

I've trying to connect to the Cloud Firestore emulator (localhost) following this link:
[https://google.dev/codelabs/firebase-emulator-get-started#0](https://google.dev/codelabs/firebase-emulator-get-started#0) 

I tried movePluginBeforeInitAuthPlugin & also tried setting it in nuxtServerInit.
If I set this.$fireStore.Gm to hosting and ssl=false before reading or writing it goes to the localhost. Can anyone please suggest where to add this code to setup emulator.

Thanks

**Comment by lupas** [comment]
Hi @suryaiiit 

Up until now we could not set the Firestore setting through this package.
But I just updated the moudle to [v4.2.2](https://github.com/nuxt-community/firebase-module/releases/tag/v4.2.2) and you can now the following in your `nuxt.config.js`:

```js
firestore: {
  settings: {
    host: 'localhost:8081',
    ssl: false
  }
},
```

Hope that helps & works :)

**Comment by lupas** [comment]
**Btw:**
Throws an error in TypeScript projects, but works without Typescript.
This will be tracked here: https://github.com/nuxt-community/firebase-module/issues/116

**Comment by suryaiiit** [comment]
I'm running into this error:

> Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object

My nuxt-config firebase settings are as below (my emulator is running at 8080 port):

```
config: {
      apiKey: '--',
      authDomain: '--,
      databaseURL: '--,
      projectId: '--,
    },
    services: {
      firestore: {
        settings: {
          host: 'localhost:8080',
          ssl: false
        }
      },
```

**Comment by lupas** [comment]
> I'm running into this error (I'm using Javascript):
> 
> > Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object
> 
> My nuxt-config firebase settings are as below (my emulator is running at 8080 port):
> 
> ```
> config: {
>       apiKey: '--',
>       authDomain: '--,
>       databaseURL: '--,
>       projectId: '--,
>     },
>     services: {
>       firestore: {
>         settings: {
>           host: 'localhost:8080',
>           ssl: false
>         }
>       },
> ```

Weird, the error only appeared for me with Typescript, it was working well with Javascript... I'll see if I can find the culprit..

**Comment by lincolnlemos** [comment]
I'm still getting errors here. I'm using the universal mode.

`Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object `

If I add the bode below suggested at https://github.com/nuxt-community/firebase-module/issues/116#issuecomment-640262146
`render: {
    bundleRenderer: {
      runInNewContext: false,
    },
 },`

The error change to:
`Firestore has already been started and its settings can no longer be changed. You can only call settings() before calling any other methods on a Firestore object.`

I'm using the same config as @suryaiiit 

If I change the mode to spa no extra code is needed and everything starts to work.

Anyone has made it work using universal mode?
