### ISSUE TITLE
[SSR] Setting firestore.settings results in "Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object"

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#116]
When setting `firestore.settings` in nuxt.config.js, we get the following error message in a ~~Typescript~~ Univerrsal (SSR) Project.

> Function Firestore.settings() requires its first argument to be of type object, but it was: a custom Object object

Works ~~without Typescript~~ in SPA mode (no SSR).

**Update:**
Culprit seems to be Universal Mode. It works on client, but fails on server:

```js
// This works
const fireStore = firebase.firestore()
if (process.client) { //
    fireStore.settings(settings)
}
// This fails
const fireStore = firebase.firestore()
fireStore.settings(settings)
```

Problem: We want it to work in SSR projects, too, obviously...

**Comment by lupas** [comment]
Seems to also be the case for pure JS proejcts as seen in https://github.com/nuxt-community/firebase-module/issues/115#issuecomment-597525511 . For me it works though, maybe not related to Typescript after all.

**Comment by rimday** [comment]
I dont use typescript but have same issue, when i add `timestampsInSnapshots` in settings

**Comment by lupas** [comment]
So it's not Typescript, but Universal mode / SSR. The error only appears on server-side:

```js
/*  In the @nuxtjs-firebase's package code */

// This works
const fireStore = firebase.firestore()
if (process.client) { //
    fireStore.settings(settings)
}
// This fails
const fireStore = firebase.firestore()
fireStore.settings(settings)
```

Problem is that in a universal app we **want it to work on both client and server**.

I'll check if this is a general issue or if it only appears in our module - might even be an issue with the FIrebase SDK.

For now updated the documentation to make this limitation clear.

**Comment by aseidma** [comment]
Any news regarding this? I am trying to run a firestore emulator locally and therefore need to change the `host` property in `firestore.settings`.

**Comment by lupas** [comment]
@aseidma 
Seems to be the same problem as we have in https://github.com/nuxt/nuxt.js/issues/7266#issuecomment-638382133.

The following seems to fix this issue:

```js
// Add this to your nuxt.config.js
render: {
    bundleRenderer: {
      runInNewContext: false
    }
  },
```

Will add this to the documentation aswell.
