### ISSUE TITLE
Firebase Auth in ssr mode using service worker

### ISSUE THREAD

**Issue by Sandeeprao69** [nuxt-community/firebase-module#120]
Hi,

I have a Nuxt App in ssr mode. Please find below link i followed to implement Server side authentication.
https://firebase.nuxtjs.org/tutorials/ssr/#firebase-auth-in-ssr-universal-mode

I have my back-end hosted at `/api/*` which uses express and mongo db. 

Issue that i am facing is each back-end call goes to `firebase-auth.js` and request does not hit the actual API. 
Please help

**Comment by lupas** [comment]
Should be fixed with v5, you can add your API to the [ignoredPaths](https://firebase.nuxtjs.org/guide/options/#ssr) option.
