### ISSUE TITLE
Auth State Persistence In Config?

### ISSUE THREAD

**Issue by benwinding** [nuxt-community/firebase-module#122]
Is it possible to modify firebase's [auth state persistence](https://firebase.google.com/docs/auth/web/auth-state-persistence) from the config? I would expect it to be implemented in the `nuxt.config.js`, but I can't seem to find it in the docs...

Here's an implementation that could work:

``` js
services: {
  auth: {
    // 'local' or 'session' or 'none'
    persistence: 'local' 
  }
}
```

Most apps just initialise it in the beginning anyway, so it would be a useful feature.

https://firebase.google.com/docs/auth/web/auth-state-persistence

**Comment by lupas** [comment]
@benwinding 
Thanks for the input, I think we're gonna include it in the next release v5 coming soon. I'll keep you posted.

**Comment by lupas** [comment]
@benwinding 
Should work as expected with the v5 release.

**Comment by benwinding** [comment]
That was fast! :grinning: 
Thanks man!
