### ISSUE TITLE
Typescript doesn't pick types

### ISSUE THREAD

**Issue by bernessco** [nuxt-community/firebase-module#127]
Shouldn't types be auto-loaded? I got it working by adding `@nuxtjs/firebase/types` to `tsconfig.json` manually.

```
{
	"compilerOptions": {
		"types": [
			"@types/node",
			"@nuxt/types",
			"@nuxtjs/firebase/types"
		]
	}
}

**Comment by lupas** [comment]
> Shouldn't types be auto-loaded? I got it working by adding `@nuxtjs/firebase/types` to `tsconfig.json` manually.

@bernessco At this point they won't be auto-loaded, no. But this works, too:
```js
"types": [
   "@nuxtjs/firebase" // without the types
]
```

If you know how to update a NPM module so the typings are automatically found by Typescript, let me know or feel free to do a PR :)

**Comment by bernessco** [comment]
Unfortunately I don't see any easy way to do so, since we declare module in `nuxt.config.js`. Solution would be to add a section in docs about typescript setup. Thanks for fast response!

**Comment by bernessco** [comment]
Found it 👍
https://github.com/nuxt-community/firebase-module/tree/master/docs/tutorials/typescript

**Comment by lupas** [comment]
Also here: https://firebase.nuxtjs.org/tutorials/typescript/

Thanks for the input, just realized the Typescript tutorial menu link went missing in the docs ;)
