### ISSUE TITLE
How to securely store the Firebase credentials

### ISSUE THREAD

**Issue by obsessen** [nuxt-community/firebase-module#129]
I would just like to ask how can I securely store the Firebase credentials. What is the best practice for this? I tried just putting it in the .env file but as soon as I do this everything stops working. I do have the dotenv module and for other variables, it works fine.

**Comment by obsessen** [comment]
So it turns out having the firebase config parameters exposed is not a problem. I learned that the protection of the services that Firebase provides should be done by using the rules in Firebase.

[Blog post that solved it for me](https://javebratt.com/hide-firebase-api/)
[Firebase rules docs](https://firebase.google.com/docs/rules)

**Comment by lupas** [comment]
@obsessen 
Yes, no need to worry about the Javascrip Client SDK credentials, these are safe to expose.

However, make sure top distinguish them from the **Admin SDK** credentials, these are critical!
E.g. when using our [SSR/serverLogin functionality](https://firebase.nuxtjs.org/guide/options/#ssr), you will need to provide these credentials and make sure to not expose them, e.g. by providing them as a separate JSON file.

In general: If you need to store/read a json from process.env, you can always store it as a string and then parse it like [so](https://stackoverflow.com/questions/48834843/authenticating-with-the-firebase-admin-sdk-using-environment-variable): 

```
const credentials = JSON.parse(process.env.MY_CREDENTIALS)
```
