### ISSUE TITLE
[SSR v5] ctx.res.locals.user undefined on server side

### ISSUE THREAD

**Issue by bunnydreams** [nuxt-community/firebase-module#131]
In the latest update to v5,`ctx.res.locals.user` is undefined in nuxtServerInit on the server side when a page is loaded afresh while logged in. This leads to the following error message on the client console when there is content conditionally loaded based on the logged in state as the server side renders content based on a non-logged in state while the client detects that the user is logged in: 
`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

This bug can be reproduced in the demo repo: https://github.com/lupas/nuxt-fire-demo

Appreciate your help in this matter!

**Comment by lupas** [comment]
Hi @bunnydreams 

I assume this is due to the sw.js not being generated by Nuxt PWA.
Can you try settings `dev: true` (and resetting your app cache for localhost) and see if that helps?

```js  
  pwa: {
      workbox: {
        importScripts: [
          '/firebase-auth-sw.js'
        ],
        // by default the workbox module will not install the service worker in dev environment to avoid conflicts with HMR
        // only set this true for testing and remember to always clear your browser cache in development
        dev: true // or better process.env.NODE_ENV === 'development'
      }
    },
```

**Comment by bunnydreams** [comment]
Ah got it. I did read the comment but I didn't realize that it had to do with the service worker. Thank you! I'm still having some issues with accessing ctx.res.locals.user on the server side when I deploy it on ZEIT Now (somehow ctx.res.locals is undefined), but I'm trying to work that out with the nuxt/now-builder team. Will make another issue here if I think there's something to do with the firebase module. Thank you!

**Comment by lupas** [comment]
Alright, hope it'll work out.

I created an issue for the nuxt-community/pwa-module to look into the possibility of adding an option to load load additional scripts (like nuxt-firebase) even in dev mode.

https://github.com/nuxt-community/pwa-module/issues/277
