### ISSUE TITLE
How to show logged in user image

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt-community/firebase-module#139]
Can I use default firebase code to show the user image or any other string

**Comment by lupas** [comment]
@rahulkumarsingh73690 
Yes. You can use all Firebase functionality with this module, such as Firebase Auth or Firebase Firestore.

Please follow our [guide](https://firebase.nuxtjs.org/guide/introduction/), and for all Firebase specific questions follow their [docs](https://firebase.google.com/docs/web/setup).

Regarding images or "another string" - of course, you can access all user related data with Firebase Auth.
