### ISSUE TITLE
this.$fireAuth inside fetch function

### ISSUE THREAD

**Issue by janpansa** [nuxt-community/firebase-module#141]
This is only a question.

Is there a way to access this.$fireAuth inside a nuxt fetch function ? I need to get the current user's idToken to place inside my headers, because I am pulling info from an api and saving that to my store.

When I try to do this inside nuxt fetch function on a page:

`this.$fireAuthObj.currentUser.getIdToken()
`

I get the following error:

`Cannot read property 'currentUser' of undefined`

Any help would be appreciated, thanks

I am using SSR: true btw...

**Comment by lupas** [comment]
@janpansa 
Could you try `this.$fireAuth` without the `obj`?

**Comment by janpansa** [comment]
@lupas , I tried it with both resulting in error. I resulted to use SPA mode for now but will continue to monitor this project as it seems like the best solution for firebase and nuxt SSR mode.

**Comment by lupas** [comment]
@janpansa 
If your goal is to get the currentUser in fetch() on serverSide via $fireAuth that will not work without server side login.

Did you set `serverLogin=true`, too, or just `SSR=true`?

ServerSide Login is experimental though and we do not recommend using it in production. https://firebase.nuxtjs.org/guide/options/#server-side-firebase-client-sdk-login

What you can do is use the ON_AUTH_STATE_CHANGED_MUTATION to set the authUser to the vuex store and then access the authUser in fetch() with e.g. `this.$store.state.authUser`. That should work.

**Comment by janpansa** [comment]
@lupas thanks for the quick reply !

I need to use this in production, so I opted to go spa mode, but still use the firebase module :)

To answer your question, I did implement ON_AUTH_STATE_CHANGED_MUTATION where I set the authUser to the vuex store. This actually works great, however, inside the fetch method, the value can be null, for example when the page refreshes and the store returns to it's Base state. During this time, the ON_AUTH_STATE_CHANGED_MUTATION takes a few seconds to kick in, about 2 - 3 seconds, where the fetch method on the server loads in less than 1 second, so the only solution there is to wait inside the fetch method and observe the authuser state from the vuex store untill it has changed from null -> actual state recieved from firebase module, but I do not like that solution.

**Comment by lupas** [comment]
@janpansa 
I just tested it again, the auth mutation should kick in before fetch. I got it working in the [demo](https://github.com/lupas/nuxt-fire-demo), see [this line](https://github.com/lupas/nuxt-fire-demo/blob/8e46588d1cc964e8342fc2c05b82342c95ca660e/components/examples/Auth.vue#L81).

However, I just releases a fix with [v5.0.7](https://github.com/nuxt-community/firebase-module/releases/tag/v5.0.7) since there was a **regression bug** with ssr auth, that might have been your problem - sorry for that.

Try again and feel free  to open a new issue in case it doesn't work.
