### ISSUE TITLE
this.$axios is undefined inside onAuthStateChanged action

### ISSUE THREAD

**Issue by alexisagos** [nuxt-community/firebase-module#146]
When using @nuxtjs/firebase and @nuxtjs/axios together, according to the [documentation](https://axios.nuxtjs.org/usage.html#store-actions), we should be able to call `this.$axios` in the store actions as it has been injected.

This works for all store actions except `onAuthStateChanged`. I'm stuck right now because I need to fetch user info every time `onAuthStateChanged` is triggerred but I can't access my axios instance.

For example:
```
onAuthStateChanged({ commit, dispatch }, { authUser }) {
	if (!authUser) {
		commit('RESET_STORE')
		return
	}

	commit('SET_USER', authUser)
	this.$axios.get('/users/me')
}
```

Is this a bug ? What workarounds can we use ?

**Comment by lupas** [comment]
Hi @alexisagos 

Have a look at the helper function [movePluginBeforeInitAuthPlugin()](https://firebase.nuxtjs.org/guide/helpers/).

The axios plugin needs to be registered before nuxt-firebase's `initAuth.js` plugin, because that plugin calls the onAuthStateChanged() before you instantiate axios.

```js
extendPlugins(plugins) {
  movePluginBeforeInitAuthPlugin(plugins, 'yourPluginName.js')
  return plugins
},
```

You can `console.log(plugins)` to see the array of registered plugins and the exact name of the plugin registered by axios.

Hope that helps.

**Comment by alexisagos** [comment]
Spot on ! Thank you very much !

By the way, there's a little mistake in the [documentation](https://firebase.nuxtjs.org/guide/helpers/).
It should be `lib` instead of `src`
`import { movePluginBeforeInitAuthPlugin } from '@nuxtjs/firebase/**lib**/helpers'`

Do you want me to submit a PR ?

**Comment by lupas** [comment]
I'd fix it myself but I like people doing PR's, that way they are already one foot in the door of contributing more to the module :P ;-)

So feel free todo a PR, if not I'll fix it when I next open my vsCode ;) 

Thanks for the tip!

**Comment by alexisagos** [comment]
I tried pushing a ne branch with the fix but permission was denied..

**Comment by lupas** [comment]
> I tried pushing a new branch with the fix but permission was denied..

You need to create a fork of the repo, push the change to your fork, and from there create a PR to the upstream master.

**Comment by alexisagos** [comment]
Sure ! My bad.

**Comment by T-Zahil** [comment]
Still happening for me 😐️

**Comment by jonnyparris** [comment]
I have just encountered this issue and I'm gutted that this `movePluginBeforeInitAuthPlugin` doesn't seem to exist anymore, along with anything to do with helpers?? 
@lupas please can you nudge me in the right direction to resolve this if you're still involved?
