### ISSUE TITLE
this.$fireAuth.signInWithEmailAndPassword resolves before state is mutated

### ISSUE THREAD

**Issue by dasblitz** [nuxt-community/firebase-module#148]
Hi I'm trying to use the firebase auth module in a Nuxt project, but I'm running into an issue.

I have no need for login in ssr, so this is all client-side only btw. I have a login page with an email/password field. Upon submitting I'd like to redirect to a `/admin` page that can only be seen when the user is logged in. So I tried the following component method in my Login.vue page component:

    async login() {
      try {
        await this.$fireAuth
          .signInWithEmailAndPassword(this.email, this.password)
          .then((result) => {
            // this happens before the ON_AUTH_STATE_CHANGED_MUTATION happens
            // so my middleware blocks the route change
            this.$router.push('/admin')
          })
          .catch(function(error) {
            // Handle Errors here.
          })
      } catch (e) {
        console.warn(e)
      }
    }

However, my `/admin` route uses middleware to check if there is a user set in my auth store. I set the user by adding an `ON_AUTH_STATE_CHANGED_MUTATION` in my auth store. This works, but the problem I'm running into is that the mutation is being executed after `signInWithEmailAndPassword` resolves. So I have no way of knowing for sure when I can call `this.$router.push('/admin')`. I can of course dispatch an action myself and wait for it to resolve, but I can't help but feel that should not be needed.

**Comment by lupas** [comment]
Hi @dasblitz 

If I were you I'd solve this like so:

```js
computed: {
   ...mapState({
      authUser: state => state.authUser
   })
},
async login() {
  try {
    await this.$fireAuth
      .signInWithEmailAndPassword(this.email, this.password)
      .catch(function(error) {
        // Handle Errors here.
      })
  } catch (e) {
    console.warn(e)
  }
},
watch: {
 authUser(val) {
    if (val) {
       this.$router.push('/admin')
    }
  }
}
```


Hope that helps.

**Comment by dasblitz** [comment]
Wow that was fast :) This is my first Vue project coming from React and I was fully unaware of the watch mechanism. I'll try it out. Tnx!

**Comment by lupas** [comment]
Guess it worked, closing the issue.
