### ISSUE TITLE
nuxt generate headers problem

### ISSUE THREAD

**Issue by ftpyz** [nuxt-community/firebase-module#155]
i add nuxtjs/firebase modules add my project and implent app.$fireStore but i generate nuxtjs generate says

```
TypeError: Cannot read property 'headers' of undefined
    at Ra (server.js:1:519924)
    at on (server.js:1:526778)
    at runNextTicks (internal/process/task_queues.js:59:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
    at async n.default (server.js:1:527804)
```

**Comment by lupas** [comment]
@ftpyz 
Can you give me more details and some code examples? Where do you call app.$fireStore? How is your project set up?

**Comment by ftpyz** [comment]
all of page example 404 not found page code. `
<script>
export default {
  layout: 'empty',
  data() {
    return {
      title: 'Ulaşmaya çalıştığınız sayfa bulunamadı'
    }
  },
  head() {
    const title = this.title
    return {
      title,
      meta: [{ hid: 'robots', name: 'robots', content: 'noindex' }]
    }
  }
}
</script>

<style scoped>
h1 {
  font-size: 20px;
}
</style>
`

in generate time 

` ERROR   /404                                                                                             19:44:27  

TypeError: Cannot read property 'headers' of undefined
    at Hi (server.js:1:226277)
    at bs (server.js:1:243192)
    at runNextTicks (internal/process/task_queues.js:59:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
    at async e.default (server.js:1:244468)`

**Comment by lupas** [comment]
@ftpyz 
I currently don't see anything related the firebase module in your code.
Could you please share the following code:

- Your `nuxt.config.js`  @nuxtjs/firebase configuration.
- The code where you use  `app.$fireStore`

The code you provided has nothing to do with this module...

**Comment by ftpyz** [comment]
nuxt.config.js `firebase: {
    config: {
      production: {
        
      },
      development: {
        
      }
    },
    customEnv: false,
    onFirebaseHosting: false,
    services: {
      auth: {
        persistence: 'local',
        initialize: {
          onAuthStateChangedMutation: 'kullanici/ataKullaniciBilgileriSenk',
          onAuthStateChangedAction: null
        },
        ssr: {
          // !! NEVER deploy a service account file to github or to a publicly accessible folder on your server !!
          // credential: '~/assets/firebase/serviceAccount.json',
          ignorePaths: ['/api/'],
          // Experimental Feature, use with caution.
          serverLogin: {
            sessionLifetime: 60 * 60 * 1000 // one hour
          }
        }
      },
      firestore: true,
      functions: {
        location: 'us-central1', // Default
        emulatorPort: null
      },
      storage: true,
      realtimeDb: true,
      performance: true,
      analytics: true,
      remoteConfig: {
        settings: {
          fetchTimeoutMillis: 60000, // Default
          minimumFetchIntervalMillis: 43200000 // Default
        },
        defaultConfig: {
          welcome_message: 'Welcome'
        }
      },
      messaging: {
        createServiceWorker: true
      }
    }
  },`

i use in store with dispatch in this.$fireStore not use in asyncData

**Comment by lupas** [comment]
@ftpyz 
Wow, you are using the full setup.. :O Do you really need all Firebase services or did you just copy+paste the entire config from the documentation? Do you really need all these services activated? Maybe start with just activating Firestore for now. 

Can you show me the code of your kullanici/ataKullaniciBilgileriSenk mutation?

**Comment by ftpyz** [comment]
i copy paste from documetation. realtime database is not active . `ataKullaniciBilgileriSenk(state, kullanici) {
    if (kullanici.authUser) {
      const user = kullanici.authUser.toJSON()
      this.$fireStore
        .collection('Kullanicilar')
        .doc(user.email)
        .get()
        .then((extra) => {
          user.EkstraKullaniciBilgileri = extra.data()
          this.commit('kullanici/ataKullaniciBilgileri', user)
          return extra.data()
        })
    }
  },`

**Comment by lupas** [comment]
Start with deactivate the services that you don't need. It's impossible to debug your code if you just copy paste things in your code and expect it to work. Please read through our [documentation](https://firebase.nuxtjs.org/) thoroughly to understand how the module works. Maybe then you will figure out where the issue lies.

It doesn't seem to be a nuxtjs/firebase related issue though, but rather something with your setup or your code.

What I can see for example is that you do the following:
```js
this.commit('kullanici/ataKullaniciBilgileri', user)
```
I'm not sure this would work. But it doesn't seem to be the issue at hand anyway.

So yeah, please remove everything from your config that you don't need yet. And then try again.

**Comment by ftpyz** [comment]
hi i solve my problem. change config remove ssr config in auth section than you

`services: {
      auth: {
        persistence: 'local',
        initialize: {
          onAuthStateChangedMutation: 'kullanici/ataKullaniciBilgileriSenk',
          onAuthStateChangedAction: null
        }
      },
      firestore: true,
      functions: {
        location: 'us-central1', // Default
        emulatorPort: null
      }
    }`
