### ISSUE TITLE
[Question] How to verify token (verifyIdToken) using $fireAuth or $fireAuthObj

### ISSUE THREAD

**Issue by chadwtaylor** [nuxt-community/firebase-module#173]
I need to verify the token before recycling it.

Via Firebase docs, you can check using the `.verifyIdToken(token)`. I tried to use the same method on $fireAuth/$fireAuthObj but keep on hitting errors. 

How would one use such a verification tool using the `$fireAuth` or `$fireAuthObj` objects?

**Comment by lupas** [comment]
What do you want to achieve? And what error messages do you get?

You probably won't need to do that.

Also note that this module is a wrapper for the Javascript SDK, not the Node.js Admin SDK. Verifying ID tokens is only available in the Admin SDK. So you'll have to setup the admin SDK yourself.

Also read through the auth part of our (documentation)[https://firebase.nuxtjs.org/guide/options/#auth], maybe the ssr option is all you need.

**Comment by chadwtaylor** [comment]
Thank you @lupas for responding. Our end users spend more than a few hours on our website. The firebase auth token is only good for an hour and then it expires.

So, I need to recycle the token after an hour has passed hence verifying whether the token is good or not before querying our API server.

Yea, I did assume we would need to use the SDK but wanted to see if this module was capable of doing so.

**Comment by lupas** [comment]
@chadwtaylor 
If you are using the Firebase SDK and Firebase Auth you won't have to bother about refreshing the token yourself, that will be handled for you.

If you are not using the SDK, then you will have to implement that yourself, you are right. This module merely integrates the Client Side SDK which has this functionality built in.

Hope you'll find a way that works for you, let me know if there's something else we can do.
