### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by m2sahin** [nuxt-community/firebase-module#191]
When I say "npm run generate" I get the error "TypeError: Cannot read property 'headers' of undefined". Also, the index.html file does not occur in the dist folder.

```
TypeError: Cannot read property 'headers' of undefined
    at yt (server.js:1:27419)
    at kt (server.js:1:31102)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
    at async e.default (server.js:1:32270)

```

I use the "Nuxt Firebase" module in my application. I think the error is caused by ssr in config file

```
// I get the error "TypeError: Cannot read property 'headers' of undefined".
    services: {
      firestore: {
        ssr: true
      },
      auth: {
        ssr: true
      }
    }

```

```
// No error during "generate"
    services: {
      firestore: {
        ssr: false
      },
      auth: {
        ssr: false
      }
    }

```
But when "ssr: false", "nuxtserverinit" doesn't work. I should definitely use Nuxtserverinit

what can I do??

**Comment by lupas** [comment]
Hey @m2sahin 

First of all, `firestore.ssr` is not an option we provide, you can delete that part. Just do `firestore: true`. See [options for firestore](https://firebase.nuxtjs.org/guide/options/#firestore).

Second: If you do `nuxt generate`, nuxt creates a static web app for you and there won't be a server that could handle SSR Auth. So `ssr: true` only makes sense when you run your application in Universal SSR mode, but not in nuxt generate.

I'll probably need to specify that better in the documentation and provide some better error messages.
