### ISSUE TITLE
TypeError: "_this.$fireAuth.GoogleAuthProvider is not a constructor"

### ISSUE THREAD

**Issue by jjangga0214** [nuxt-community/firebase-module#192]
### Version

@nuxtjs/firebase: 5.2.0
firebase: 7.14.2
nuxt: 2.0.0

### Reproduction Link

It's simple, so I omitted it. If you think it's really needed, please request it. 

### Steps to reproduce

```js
const provider = new this.$fireAuth.GoogleAuthProvider()
```

### What is Expected?

Successfully create an AuthProvider object.

### What is actually happening?

This error occurs.

```
TypeError: "_this.$fireAuth.GoogleAuthProvider is not a constructor"
```

**Comment by lupas** [comment]
@jjangga0214 

What you are doing is `firebase.auth().GoogleAuthProvider()`, but you need to do `firebase.auth.GoogleAuthProvider()`.

Try this:
```js
const provider = new this.$fireAuthObj.GoogleAuthProvider()
```

The `$fireAuthObj` is a reference to the auth service, while `$fireAuth` is a reference to the service instance itself.

See: https://firebase.nuxtjs.org/guide/usage/#general-usage

**Comment by jjangga0214** [comment]
@lupas Yes, that's right :)
Thanks so much for prompt response!

**Comment by sugoidesune** [comment]
Since V7 this is now 

```js
var provider = new this.$fireModule.auth.GoogleAuthProvider();
```

**Comment by Antoinebr** [comment]
The full working code as of now : 

```JavaScript 
           async googleSignIn(){

                const provider = new this.$fireModule.auth.GoogleAuthProvider();
                
                try {
                    await this.$fire.auth.signInWithPopup(provider);
                    console.log('Now registered with Google 🔥')
                } catch (error) {

                    console.log('❌', error)
                }
                
            }
```
