### ISSUE TITLE
Authenticated user is always null

### ISSUE THREAD

**Issue by watsab** [nuxt-community/firebase-module#195]
Hi ! 

I'm stuck with an issue that I don't know how to solve : the user in the store action defined the nuxt.config.js of my project is always empty.
I've read the documentation but I cannot see what I've done wrong. Can you help me ? 
Here is the module configuration as I have it in the nuxt.config.js:
```js
firebase: {
    config: {
      apiKey: process.env.FB_API_KEY,
      authDomain: process.env.FB_AUTH_DOMAIN,
      databaseURL: process.env.FB_DB_URL,
      projectId: process.env.FB_PROJECT_ID,
      storageBucket: process.env.FB_STORAGE_BUCKET,
      messagingSenderId: process.env.FB_MESSAGING_SENDER_ID,
      appId: process.env.FB_APP_IP,
      measurementId: process.env.FB_MEASUREMENT_ID
    },
    services: {
      auth: {
        persistence: 'local',
        initialize: {
          onAuthStateChangedAction: 'user/updateUserId'
        }
      },
      firestore: true
    }
  },
```

And here is my user store: 
```js
const initialState = {
  id: null
};

export const mutations = {
  reset: (state) => {
    const s = initialState;
    Object.keys(s).forEach((key) => (state[key] = s[key]));
  },

  setId: (state, id) => {
    state.id = id;
  }
};

export const actions = {
  updateUserId: (context, { authUser }) => {
    if (!authUser) {
      context.commit('setId', null);
      return;
    }

    context.commit('setId', authUser.uid);
  }
};
```

The problem is that is the 'updateUserId' function, authUser is always empty (and so is the claims object). Do you see any reason why ?

Thanks!

**Comment by lupas** [comment]
@watsab 
Hmmm... your code seems fine.

Are you by chance importing/initializing Firebase somewhere else in your code?

**Comment by watsab** [comment]
ok ! my bad... I actually forgot to sign in the user 🤦 ... I guess that's the sort of things to happen when you code for the 4th night in a row... anyway thanks for your help and also the plugin ! It's just perfect !

**Comment by lupas** [comment]
@watsab 
Haha, that can happen ;) Glad it works now and you're happy with the plugin. Go get some sleep now :P
