### ISSUE TITLE
Cannot read property 'messaging' of undefined

### ISSUE THREAD

**Issue by alexiej** [nuxt-community/firebase-module#197]
"firebase": "^7.14.2",
    "nuxt": "^2.0.0"
    "@nuxtjs/firebase": "^5.2.0",

I try to go through the documentation but I always got error.
1. I cannot find the nuxt.config.js file. I think now it is config/nuxt.js.
2. when I add to the modules the configuration for the firebase I've got the error.

```
Cannot read property 'messaging' of undefined                                                                                                                                       12:30:15

  at ModuleContainer.module.exports (node_modules/@nuxtjs/firebase/lib/module.js:15:38)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:215:34)
  at node_modules/@nuxt/utils/dist/utils.js:1803:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:43:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:685:5)

TypeError: Cannot read property 'messaging' of undefined
```

```
modules: [
    [
      '@nuxtjs/firebase',
      {
        config: {
          apiKey: '<apiKey>',
          authDomain: '<authDomain>',
          databaseURL: '<databaseURL>',
          projectId: '<projectId>',
          storageBucket: '<storageBucket>',
          messagingSenderId: '<messagingSenderId>',
          appId: '<appId>',
          measurementId: '<measurementId>'
        },
        services: {
          auth: true // Just as example. Can be any other service.
        }
      }
    ]
  ],
```

I think that I miss something important, but I cannot find what.

**Comment by lupas** [comment]
> 1. I cannot find the nuxt.config.js file. I think now it is config/nuxt.js.

The nuxt.config.js is essential for your nuxt app, how have you set up your nuxt app?

https://nuxtjs.org/guide/directory-structure#the-nuxt-config-js-file

> when I add to the modules the configuration for the firebase I've got the error.

Seems like you are using messaging but not setting it up.

```js
services: {
          auth: true // Just as example. Can be any other service.
          messaging: true // <-----
        }
```

Please read through the nuxt documentation and our documentation one more time. Your questions are answered in there.

**Comment by 93lucasp** [comment]
@lupas i have the same problem you can check it [here](https://github.com/nuxt-community/firebase-module/issues/637) do you have any idea about that?
