### ISSUE TITLE
Retrieve idToken on nuxtServerInit

### ISSUE THREAD

**Issue by EmmanuelVlad** [nuxt-community/firebase-module#202]
### Is your feature request related to a problem? Please describe.
I'm trying to retrieve the idToken on `nuxtServerInit` so that I can store it in a cookie and start doing API requests with it.

### Describe the solution you'd like
A solution would be to add `idToken` to the user object like so:
###### ssrAuth.js
```js
res.locals = {
  ...res.locals,
  user: {
    ...{ idToken, ...authUser },
    allClaims: decodedToken
  }
}
```

**Comment by lupas** [comment]
Fixed with [v6.0.0](https://github.com/nuxt-community/firebase-module/releases/tag/v6.0.0), thanks for the PR!
