### ISSUE TITLE
res.locals.user exists on nuxtServerInit but $fireStore results to Missing or insufficient Permission

### ISSUE THREAD

**Issue by arsy29** [nuxt-community/firebase-module#205]
After Authentication additional user details and configuration are being pulled from firestore. When the user logs in it goes through without a problem. The problem comes when you refresh it. auth credentials are being rehydrated as can be seen in nuxtServerInit res.locals.user, but fetching data from firestore causes Missing or insufficient permissions error.

Here is the code in nuxtServerInit.
```js
async nuxtServerInit({ dispatch, commit }, { res }) {
  // await context.dispatch('content/fetch', 'home')
  if (res && res.locals && res.locals.user) {
    const { allClaims: claims, ...authUser } = res.locals.user
    await dispatch('account/initAccount', authUser.uid);			
  }
}
```

here is the code for account/initAccount.
```js
async initAccount(context, payload){
  try{
    let doc = await this.$fireStore
      .collection('userConfig')
      .doc(payload)
      .get();
    if(doc.exists){
      let account = { uid: doc.id, ...doc.data()};
      context.commit('setAccount', account);
      return account;
    }
  }catch(err){
    console.log(err);
  }
}
```

**Comment by lupas** [comment]
Hey @arsy29 

Sorry for the late response.
This still running into this problem? If properly set up, this should work. 

Do you have everything configured as described [here](https://firebase.nuxtjs.org/tutorials/ssr/#firebase-auth-in-ssr-universal-mode)? (workbox, firebase-admin installed and so on?)

**Comment by lupas** [comment]
No answer for 17 days, closing issue.

**Comment by sorxrob** [comment]
> Hey @arsy29
> 
> Sorry for the late response.
> This still running into this problem? If properly set up, this should work.
> 
> Do you have everything configured as described [here](https://firebase.nuxtjs.org/tutorials/ssr/#firebase-auth-in-ssr-universal-mode)? (workbox, firebase-admin installed and so on?)

Hi same here, everything was properly configured. Removing security rules made it work though.

FYI I'm not authenticating using serviceAccount

**Comment by dhara15101991** [comment]
I am facing same issue. Cannot authenticate user and it shows `Missing or insufficient permissions`.

**Comment by dosstx** [comment]
Yea, I'm getting the same thing. It's as if the user auth object is not done loading or something (I am not using SSR and I am also putting the data fetch in mounted() hook). Here are my security rules:

```
  // Returns `true` if the requested post is 'published'
  // or the user authored the post
  function authorOrPublished() {
      return resource.data.published == true || request.auth.uid == resource.data.uid;
  }
  
  // Required for collection group queries; 
  // declare that ANY path that ends with "posts" can be readable
  // https://firebase.google.com/docs/firestore/security/rules-query#secure_collection_group_queries_based_on_a_field
    match /{path=**}/posts/{postSlug} {
    
    	// Anyone can query published posts
      // Authors can query their unpublished posts
      allow list: if authorOrPublished();

      // Anyone can retrieve a published post
      // Authors can retrieve an unpublished post
      allow get: if authorOrPublished();
  }
  ```

Here are is my fetch code:

```
  async mounted() {
    await this.getPostFeed()
  },
  methods: {
    async getPostFeed() {
      try {
        const postsArr = []
        const colRef = this.$fire.firestore
          .collection(`users/${this.$route.params.uid}/posts`)
          .orderBy('createdAt', 'desc')
        const querySnapshot = await colRef.get()
        querySnapshot.forEach((doc) => postsArr.push(doc.data()))
        this.posts = postsArr

      } catch (error) {
        console.error('error fetching posts', error)
      }
    }
    ```
