### ISSUE TITLE
SSR on Cloud Function, ok for prototype. For production, what's your favorite hosting ?

### ISSUE THREAD

**Issue by DoIB** [nuxt-community/firebase-module#207]
Hi everyone,
I have a question. SSR is great to rendering a page server side.

I tested on cloud function but 6s to render a page is too slow (warm up
then it's ok = so it's great to prototying but not an option for production).

Then, the cost of App engine seems too high to be an option for small applications.

--
What is your favorite hosting for an SSR nuxt website ? :)

--

Thanks for your help. Take care ^^

**Comment by sambessey** [comment]
I had this question/ problem too. Like you I wanted to use Cloud functions but could not tolerate the cold- start times. In short, you have to go with a 'stateful' service.

I was hopeful Vercel was viable as they are big advocates of React's Next framework and from what I read, their service avoids cold latency. However they do not support Nuxt in Universal mode as it is a 'community project'. As a side note, I have a PWA hosted with them and the performance is excellent.

For Nuxt, I ended up using Dokku on Digital Ocean's VPS. So far I am really liking it. The setup wasn't that painful and 2x VPS behind a load balancer running multiple instances of the app in Nuxt is working out at about $30 a month I think (Which is OK). Performance is pretty good - about the same as a warmed Cloud Function.

**Comment by lupas** [comment]
Closing this since it seems to be answered and is also not really specific to this module.
