### ISSUE TITLE
Using jest and vuex with nuxt-fire

### ISSUE THREAD

**Issue by Thomaswaldick** [nuxt-community/firebase-module#214]
I use nuxt fire in my vuex modules for numerous things, mainly interacting with the firestore using this.$fireStore. I'm working on implementing unit tests for these vuex modules but getting an error "TypeError: Cannot read property 'collection' of undefined" when trying to dispatch a command in my test. I also tried testing the fireStore directly in my test by mocking it roughly following: https://stackoverflow.com/a/60049913 but ran into the same error. Any help would be great!

**Comment by lupas** [comment]
Hey @Thomaswaldick 

Could you provide a basic example on Codepen or similar where you run into this issue?

**Comment by Thomaswaldick** [comment]
@lupas I'll try to get you that. I guess the main issue I have is I'm not sure what's the best way to use something like $fireStoreObj in a js file. Is there a good way to import it?

**Comment by lupas** [comment]
> @lupas I'll try to get you that. I guess the main issue I have is I'm not sure what's the best way to use something like $fireStoreObj in a js file. Is there a good way to import it?

You should be able to access the same as _$fireStoreObj_ like so in your tests:
```js
import firebase from 'firebase/app'
import 'firebase/firestore'

const fireStoreObj = firebase.firestore

// So this should be available without Firestore being instantiated
fireStoreObj.FieldValue.serverTimestamp())
```

But if you need to access the Firestore instance like `$fireStore`, I guess you would have to instantiate Firebase yourself for your tests.
