### ISSUE TITLE
IE11 Object.values Polyfill

### ISSUE THREAD

**Issue by Scaalees** [nuxt-community/firebase-module#217]
In IE11 I am getting an error for Object.values within firebase.

`Object doesn't support property or method 'values'`

Is there an option to use polyfill?

**Comment by JFGHT** [comment]
This is not related to firebase-module but to firebase jsdk itself. I'd recommend you to search for information on how to use `core-js` to fix these compatibility problems.

**Comment by lupas** [comment]
Closing since not related to the module, googling should provide plenty of solutions for this issue.
