### ISSUE TITLE
How to use the module in nuxt.config.js

### ISSUE THREAD

**Issue by Aurion72** [nuxt-community/firebase-module#227]
Hello,

I use @nuxtjs/sitemap to generate my sitemap and I would like to add my news stored on firebase.
According to the doc of @nuxtjs/sitemap I should do :

```js
routes: async () => {
/* retrieve here the news */
}

I've been trying 

routes: async () => {
      const news = await $fireStore
      .collection("news")      
      .orderBy("published_at", "desc")
      .limit(2)
      .get()
      .then((snap) => {
        return snap.docs.map(doc => doc.data())
      }); 
}
```

But that doesn't work, it say "$fireStore is not defined" any ideas?

**Comment by lupas** [comment]
That won't work because at nuxt startup (i.e. in your nuxt.config.js) Nuxt modules/plugins and therefore also this module are not initialized yet.

I solve this same issue like so:
```js
// Nuxt.config.js
import getRoutes from './assets/js/getRoutes.js'
import firebaseConfig from './assets/firebaseConfig'

export default async () => {
  ...
    modules: [
      [
        '@nuxtjs/sitemap',
        {
          routes: await getRoutes(),
        },
      ],
    ],,
    buildModules: [
      [
        '@nuxtjs/firebase',
        {
          config: firebaseConfig,
          services: {
            firestore: true,
          },
        },
      ],
    ],
}
```

```js
// ./assets/js/getRoutes.js
import firebase from 'firebase/app'
import 'firebase/firestore'
import firebaseConfig from '../../assets/firebaseConfig'

export default async function () {
  if (!firebase.apps.length) {
    firebase.initializeApp(firebaseConfig)
  }
  const fireStore = firebase.firestore()
...
```

I know it's not fun to initialize Firebase twice, but at this point I don't see another option. If anyone has a better idea, let us know.

Hope that helps.

**Comment by simeon9696** [comment]
> Hello,
> 
> I use @nuxtjs/sitemap to generate my sitemap and I would like to add my news stored on firebase.
> According to the doc of @nuxtjs/sitemap I should do :
> 
> ```js
> routes: async () => {
> /* retrieve here the news */
> }
> 
> I've been trying 
> 
> routes: async () => {
>       const news = await $fireStore
>       .collection("news")      
>       .orderBy("published_at", "desc")
>       .limit(2)
>       .get()
>       .then((snap) => {
>         return snap.docs.map(doc => doc.data())
>       }); 
> }
> ```
> 
> But that doesn't work, it say "$fireStore is not defined" any ideas?

If you're dynamically generating your routes, you don't need to worry. The sitemap will automatically handle it for you.  Taken from [this question](https://stackoverflow.com/questions/57501556/nuxt-dynamic-routing-on-firebase?noredirect=1&lq=1)

```
generate: {
    async routes() {
      const { db } = require('./services/fireInit'); //or wherever your firebase plugin is being exported from
      const qs = await db.collection('recipes').get();
      return qs.docs.map(x => `/recipes/${x.id}`);
    }
  },
```
