### ISSUE TITLE
Change Project Programatically

### ISSUE THREAD

**Issue by andyfensham** [nuxt-community/firebase-module#229]
I have many firebase projects and want to build a single administration site for that using Nuxt Firebase.

How can I programatically switch between projects instead of setting the projects up in nuxt config.

**Comment by lupas** [comment]
Hi @andyfensham 

At this point this is not possible with the @nuxtjs/firebase module. For special cases like this I would advice you to implement the Firebase JSD SDK yourself, I don't believe this need is that common that we will implement such a functionality into this module.
