### ISSUE TITLE
Support delayed service initialization

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/firebase-module#231]
### Is your feature request related to a problem? Please describe.

At the moment if you use this module all firebase services are included / initiated on every page. I dont want / need this

### Describe the solution you'd like

Support delayed loading / initialization of firebase services at the user's request

### Describe alternatives you've considered

Do everything manually without this module

### Additional context

For example, I only need fireAuth when a user decides to login (am using custom token based login). If a user isn't logged in then I dont need to include fireAuth _yet_. Some with realtimeDb, I am only using it on a single page

**Comment by lupas** [comment]
Hey @pimlie 

Thanks for the feature request.
You're right, currently this is not possible with the way the module is built.

We could - probably best *additionally* to the all-in solution - export specific functions that instantiate a service when requested, so one could import that wherever needed and it automatically sets up the service with the provided credentials from nuxt.config.

That would require quite some brain-cells and refactoring I assume, I'll see what I can do, currently bit low on my time budget. So mostly likely won't be today or tomorrow.

Let me know if you already have a plan on how we best could achieve this.

**Comment by pimlie** [comment]
There are multiple options for an API, am currently thinking about using something like this (but still a wip):

```js
  const fire = {}

  <% if (options.services.auth) { %>
  /** --------------------------------------------------------------------------------------------- **/
  /** -------------------------------------- FIREBASE AUTH ---------------------------------------- **/
  /** --------------------------------------------------------------------------------------------- **/

  let authReady = false

  fire.auth = {
    service: null,
    session: null,
    ready() {
      if (authReady) {
        return this.session
      }
      // third arg true is to remove the await from the import statement
      return <%= writeImportStatement('auth', false, true) %>.then(() => {
        this.session = session.auth()

        inject('fireAuth', this.session)
        this.service = firebase.auth

        // dont need persistence stuff atm so havent included that (yet)

        authReady = true
        return this.session
      })
    }
  }

  <% } %>

  ctx.$fire = fire
  inject('fire', fire)
```

Then in my app I can do:
```js
const auth = await ctx.$fire.auth.ready()
auth.signInWithCustomToken(token)
```

But still eg thinking about whether I think its a good idea to also keep injecting $fireAuth, it is 'short' but why support two ways of accessing the same object. You can just do `ctx.$fire.auth.session`, was thinking about replace `ctx.$fire.auth` with the full `session` and then adding `ready` on the session object. But dont think we should add our own methods to the firebase auth api
