### ISSUE TITLE
How access to this.$fireMess from nuxtServerInit

### ISSUE THREAD

**Issue by MSkred** [nuxt-community/firebase-module#232]
Hello, 

Previously I think we can access to `this.$fireMess.getToken()` from the `nuxtServerInit` action but now if I `console.log()` this is `return undefined`.

Someone know if it's possible to access to $fireMess from the first action ?

**Comment by lupas** [comment]
Firebase Messaging is only available on the client and therefore cannot be called in nuxtServerInit.

If you want to get the token on client-init, you could do that e.g. in a a client-side only [nuxt plugin](https://nuxtjs.org/guide/plugins/).
