### ISSUE TITLE
Error: Module `@nuxtjs/firebase` not found.  

### ISSUE THREAD

**Issue by limsocheat** [nuxt-community/firebase-module#234]
Try to install @nuxtjs/firebase on fresh project. 
got bellow error: 

```
 FATAL  Module @nuxtjs/firebase not found.                                                                                                          11:20:36  

  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:182:17)
  at node_modules\@nuxt\utils\dist\utils.js:1803:43
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:43:5)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:685:5)


   ╭─────────────────────────────────────────────────╮
   │                                                 │
   │   ✖ Nuxt Fatal Error                            │
   │                                                 │
   │   Error: Module `@nuxtjs/firebase` not found.   │
   │                                                 │
   ╰─────────────────────────────────────────────────╯
```

nuxt.config.js
```
modules: [
    [
      '@nuxtjs/firebase',
      {
        config: {
          apiKey: '<apiKey>',
          authDomain: '<authDomain>',
          databaseURL: '<databaseURL>',
          projectId: '<projectId>',
          storageBucket: '<storageBucket>',
          messagingSenderId: '<messagingSenderId>',
          appId: '<appId>',
          measurementId: '<measurementId>'
        },
        services: {
          auth: true // Just as example. Can be any other service.
        }
      }
    ]
  ],
```

**Comment by lupas** [comment]
Hmm, that should work if you have the module installed.

Did you do?

```sh
yarn add @nuxtjs/firebase
# OR
npm i @nuxtjs/firebase
```

See install guide:
https://firebase.nuxtjs.org/guide/getting-started/#install

**Comment by Tadasb** [comment]
It's not working. I tried removing node_modules and installing them again and it didn't help either. The folder is there, but this error shows all the time when running `npm run dev`. 
When running `npm run generate` it throws a fatal error saying: 
`Error: Module `@nuxtjs/firebase` not found. Please ensure `@nuxtjs/firebase` is in `dependencies` and installed. `

**Comment by limsocheat** [comment]
> Hmm, that should work if you have the module installed.
> 
> Did you do?
> 
> ```shell
> yarn add @nuxtjs/firebase
> # OR
> npm i @nuxtjs/firebase
> ```
> 
> See install guide:
> https://firebase.nuxtjs.org/guide/getting-started/#install

I always use npm to install package. I see the folder **@nuxtjs/fireabase** inside _node_modules_ folder, I tried to delete _package.lock.json_, delete whole _node_models_ and reinstall with npm, but know luck. 

**then, I tried to install Yarn & install package with yarn, it works.** 
Please check the problem with npm. thanks.

**Comment by limsocheat** [comment]
> Don't forget to do
> `npm i firebase`

`npm i firebase` **get error package name firebase not found.** 
then I tried with yarn add firebase.
it works.

not sure what problem with npm
