### ISSUE TITLE
Missing instructions for Firebase Hosting

### ISSUE THREAD

**Issue by SameeranB** [nuxt-community/firebase-module#246]
I am unable to find any instructions on how to host my project on Firebase Hosting. I tried a few tutorials that explained how to host the project without the use of the firebase-module, but all of them are too old. The structure of the nuxt projects has changed quite a bit since then. I also tried to do it myself, but that didn't work out either. I went through the demo project, but I can't seem to find all the required configuration to successfully host.

**Comment by lupas** [comment]
Hi @SameeranB 

This question is a general nuxt/firebase question and has nothing to do with this module.
Please ask such questions on stackoverflow, this issue board is meant for module specific questions, bugs & feature requests.

Btw:
If you ask it there, please make sure to include your nuxt setup. Are you using **nuxt generate** and plan to deploy a static site? Or are you running **universal mode** and want to server-render your render content? That's quite the key question when it comes to how to deploy a nuxt app.
