### ISSUE TITLE
Is there a way to manualy unsuscribe the `$fireStore` snapshots listeners?

### ISSUE THREAD

**Issue by robertocifuentes** [nuxt-community/firebase-module#248]
I've started to add some real-time data to may app by using `onSnapshot` listeners in the `.mounted()` hook. 

But if they are not unregistered, these listeners will in fact, listen for every change in the database, whether you are in a relevant page or not.

This behavior has side effects in both data and battery consumption. So i was wondering whats the best way to add and remove `.onSnapshots()` listeners? 

I've been unable to find guidance in the docs. Thanks for reading me. @lupas Congrats on the module Itś great!! Chapeau!!

**Comment by lupas** [comment]
Hey @robertocifuentes 

Thanks for the chapeau 🎩.

This is no module-specific problem, therefore we're not mentioning a solution to this in our docs. If you setup Firebase without this library you'd have to manually unsubscribe these listeners, too. 

You can solve it like so:

```vue
<script>
export default {
  data: () => ({
     unsubscribeFooListener: null
  }),
  mounted: {
     // Setup the listener
     this.unsubscribeFooListener = ref.onSnapshot(...)
  },
  destroyed: {
    // destroy the listener when leaving the view
     this.unsubscribeFooListener()
  }
}
</script>
```


Hope that helps :)

br, Pascal

**Comment by robertocifuentes** [comment]
It's clear and clever to implement it this way. I've only used this module for 3 days and I'm already excited with all firebase features added to nuxt so easily. Thanks again for your answer! Have a nice day!
