### ISSUE TITLE
Middleware & User Authentication

### ISSUE THREAD

**Issue by sambessey** [nuxt-community/firebase-module#252]
Hi 

Thanks for writing and maintaining this fantastic module for Nuxt - it mostly works wonderfully!

One thing I can't work out - I am trying to protect certain routes via middleware, but if I take a given route like /secret-page, the advice given in [issue 28](https://github.com/nuxt-community/firebase-module/issues/28) does not seem to work for me (specifically for the scenario where I navigate directly to that page via typing in the URL). I am developing in Universal Mode. I tried the mounted approach described there but still the Vuex state (with the user auth) is not seen by my app (Because I am working in Universal mode..?). I believe this is expected behaviour.

As I understand it, there is no easy way to use Middleware on the server side to authenticate/ redirect, so the advice is to wrap the middleware logic in `if (!process.server)`/ `if (process.browser)` to execute client- side. Problem is that Middleware only seems to run server side upon browsing directly to a page. This behaviour is described in the Nuxt docs. 

So what is the best way to achieve the desired outcome? Would putting some code in the mounted hook of my template be a better approach? or am I missing something really fundamental here? 

Thanks

**Comment by zernonia** [comment]
You can try out something like this if you are using Vuex for storing `onAuthChanges`,

`.middleware/auth.js`

```
export default function({ store, redirect, route, app }) {
  store.state.user.id == '' && route.name =='secret-page' ? redirect('/login') : ''  
  store.state.user.id != '' && route.name =='login' ? redirect('/secret-page') : ''  
}
```

**Comment by sambessey** [comment]
Hi Zeronia 

As per my comments above, the state does not seem to be available when navigating directly to a page as middleware executes server side only when navigating directly to a route in Universal mode

Thanks!

**Comment by zernonia** [comment]
> Hi Zeronia
> 
> As per my comments above, the state does not seem to be available when navigating directly to a page as middleware executes server side only when navigating directly to a route in Universal mode
> 
> Thanks!

Did you follow the tutorial regarding the firebase ssr on the website? If so, you should have configured nuxtServerInit properly, and your Vuex data will be available for middleware.

**Comment by sambessey** [comment]
Hi Zeronia 

I thought I had, but I will check this again - thanks. 
It is good to know that it should work if everything is configured correctly.

**Comment by sambessey** [comment]
Ok here is the problem:

NuxtServerInit action fires but never meets the criteria for the if statement (i.e. I never get anything logged) because res.locals is null:

`    if (res && res.locals && res.locals.user) {
      console.log("nuxtServerInit Fired", res.locals);`

I will try and find a solution but this is where it goes wrong for no apparent reason.

Thanks

**Comment by zernonia** [comment]
> Ok here is the problem:
> 
> NuxtServerInit action fires but never meets the criteria for the if statement (i.e. I never get anything logged to console) because res.locals is null:
> 
> ` if (res && res.locals && res.locals.user) { console.log("nuxtServerInit Fired", res.locals);`
> 
> I will try and find a solution but this is where it goes wrong for no apparent reason.
> 
> ******EDIT******
> 
> Ok I worked out what is going on... Everything was working fine, but I was accessing my Nuxt app through a non-secure (http) host. (Local IP on my network).
> 
> The Service Worker does not work correctly in this case, so switching to localhost seems to have fixed it for now. Makes testing a pain though ;-)
> 
> Thanks all!

Glad I could help. Enjoy!
