### ISSUE TITLE
onSnapshot() vs get() in Nuxt when using asyncData()

### ISSUE THREAD

**Issue by dosstx** [nuxt-community/firebase-module#255]
I am new to Nuxt and also to Firebase. I noticed an issue when using `onSnapshot()` vs `get()` in  Nuxt and wondering if someone can help me with it. 

Here it is:

WhenI use the following `.get()` code to grab and display photo docs on a page, I have no problems:

```
 async asyncData({ app, error }) {
    const photosArr = []
    const docRef = await app.$fireStore.collection('photos').get()
    try {
      docRef.forEach((doc) => photosArr.push(doc.data()))
      return {
        photos: photosArr
      }
    } catch (e) {
      error({
        statusCode: 503,
        message: 'Unable to fetch posts at this time. Please try again.'
      })
    }
  },
```

However, if I use the `.onSnapshot()` listener instead of `.get()`, I dont' have any errors in console, but I noticed sometimes the photos load and sometimes they dont'. The only way I can get the photos to load is by navigating away and coming back to the photos page. Here is my `onSnapshot` code:

```
async asyncData({ app, error }) {
    const photosArr = []
    const docRef = await app.$fireStore.collection('photos')
    try {
      docRef.onSnapshot((querySnapshot) => {
        querySnapshot.forEach((doc) => {
          photosArr.push(doc.data())
        })
      })
      return {
        photos: photosArr
      }
    } catch (e) {
      error({
        statusCode: 503,
        message: 'Unable to fetch posts at this time. Please try again.'
      })
    }
  },
```

Any tips on how I can successfully use onSnapshot instead of get() ?
NO issues in my vanilla vue app, but when I use Nuxt, I get the above issue. If there is a better way to write the code for onSnapshot, let me know. Thanks for your help.

**Comment by dosstx** [comment]
This is weird (when using onSnapshot) , something happens to client:

![image](https://user-images.githubusercontent.com/6342102/87039631-142dab00-c1b5-11ea-91eb-f38fa4dd94b8.png)

**Comment by dosstx** [comment]
OK after some further digging, I separated the asyncData from the client like so:

```
async asyncData({ app, error }) {
    const photosArr = []
    const docRef = await app.$fireStore.collection('photos').get()
    try {
      docRef.forEach((doc) => photosArr.push(doc.data()))
      return {
        photos: photosArr
      }
    } catch (e) {
      error({
        statusCode: 503,
        message: 'Unable to fetch posts at this time. Please try again.'
      })
    }
  },
  data() {
    return {
      clientPhotos: [],
      isLoading: false,
      selected: 'all',
      options: [
        { text: 'All', value: 'all' },
        { text: 'Unsolved', value: 'unsolved' },
        { text: 'Solved', value: 'solved' }
      ]
    }
  },
  mounted() {
    this.allclientPhotos()
  },
  methods: {
    onSort(evt) {
      if (evt === 'solved') {
        this.solvedPhotos()
      } else if (evt === 'unsolved') {
        this.unSolvedPhotos()
      } else {
        this.allclientPhotos()
      }
    },
    allclientPhotos() {
      try {
        this.$fireStore.collection('photos').onSnapshot((snapShot) => {
          const snapData = []
          snapShot.forEach((doc) => {
            snapData.push(doc.data())
          })
          this.clientPhotos = []
          this.clientPhotos = snapData
        })
      } catch (error) {
        console.log('Error getting all docs: ', error)
      }
    }
  },
```
and then in the <template> section I made the call to the client photos like so:

`<div v-for="photo in clientPhotos" :key="photo.id"> `

I got the above workflow based on your response here:

https://medium.com/p/b424ee0fcb4e/responses/show

Let me know if I"m not doing it the best way. Thank you very much for your work in this plugin!

**Comment by eherediadev** [comment]
> Now...new question:
>
> Can I safely use VueFire's this.$bind syntax for my client side code?

Hey @dosstx , did you find the answer to this question?
