### ISSUE TITLE
Cannot retrieve the server user in Universal Mode via `nuxt generate`

### ISSUE THREAD

**Issue by taish** [nuxt-community/firebase-module#257]
# About Firebase Authentication

## Goal

I want to retrieve the user using `nuxtServerInit` in Universal Mode as follows
https://firebase.nuxtjs.org/tutorials/ssr/

## Problem

I can’t retrieve the user only using `nuxt generate`.
I can retrieve the user only development environment.

## Reason

Because not available `context.res` via `nuxt generate`
ref:  https://nuxtjs.org/api/context/#-code-res-code-a-href-https-nodejs-org-api-http-html-http_class_http_serverresponse-em-http-response-em-a-

**Is there any way to retrieve the user using `nuxtServerInit` via `nuxt generate` ?**

**Comment by lupas** [comment]
Hey @taish 

Nuxt generate generates static html pages, there won't be a server and therefore no ** nuxtServerInit** that will be called when a user visits your website. Therefore, there won't be a user available for you to access in nuxtServerInit.

NuxtServerInit will only run once once during the generation command on your pre-rendering server (or your local machine), but obviously during that process no user is being logged in, so you won't get any user object.

What are you trying to achieve? If you use nuxt generate, there won't be SSR - nuxt generate is pre-rendering.

**Comment by taish** [comment]
@lupas thanks for explanation. I understand and resolved!
