### ISSUE TITLE
How to access $fireAuth from nuxt auth scheme? 

### ISSUE THREAD

**Issue by zachu90** [nuxt-community/firebase-module#268]
I have created a custom auth scheme as described in nuxt auth module [docs](https://auth.nuxtjs.org/guide/scheme.html#creating-your-own-scheme).

The user is authenticated with my own API which returns JWT. 

Once the user is authenticated I want to call firebase method signInWithCustomToken as described [here](https://firebase.google.com/docs/auth/web/custom-auth#authenticate-with-firebase)

The scheme file is located in schemes\customScheme.js

It simply extends local scheme, all I want to add is an extra call to signInWithCustomToken to log in authenticated user to firebase.

```
import LocalScheme from '@nuxtjs/auth/lib/schemes/local'

export default class CustomScheme extends LocalScheme {
  mounted () {
    if (this.options.tokenRequired) {
      const token = this.$auth.syncToken(this.name)
      this._setToken(token)
    }

    console.log(app.$fireAuthObj) //undefined
    console.log(this.$fireAuthObj) //undefined
    console.log(app.$fireAuth) //undefined
    console.log(this.$fireAuth) //undefined

    return this.$auth.fetchUserOnce()
  }
}
```

Is there a way to access $fireAuth from the customScheme.js ?

**Comment by lupas** [comment]
Hey @zachu90 

Could you try to approach mentioned [here](https://github.com/nuxt-community/firebase-module/issues/166#issuecomment-617985939)?

**Comment by zachu90** [comment]
@lupas Thank you for the reply ! 

Sorry I just saw it.

I tried the solution you suggested, and it ALMOST works.

```
import LocalScheme from '@nuxtjs/auth/lib/schemes/local'

let fireStore = null
export const _setupFirestore = (fs) => {
  fireStore = fs
  console.log(fireStore) // IT PRINTS THE FIRESTORE INSTANCE CORRECTLY
}

export default class CustomScheme extends LocalScheme {
  mounted() {
    console.log(fireStore) // null
  }
}
```

If I print `fireStore` inside `export const _setupFirestore...` the variable contains `fireStore` instance which is correct.

However if I try to access it inside `class`, it is `null`.


Any idea why?
