### ISSUE TITLE
authUser returns Null to the middleware but is Populated after Mount

### ISSUE THREAD

**Issue by kpguru20001** [nuxt-community/firebase-module#271]
Hi 
I have bee trying to test if user is logged in using the getter isLoggedIn which was returning false to the middleware but after logging the store and getter after mounted they return true with the authUser object

**Comment by lupas** [comment]
Please use the issue template to create an issue and provide code examples or a reproduction link, otherwise it's impossible to see what is wrong in your code. Thanks.
