### ISSUE TITLE
XMLHttpRequest SSR Error

### ISSUE THREAD

**Issue by JFGHT** [nuxt-community/firebase-module#273]
### Version
@nuxtjs/firebase: 6.1.1
firebase: 7.17.1
nuxt: 2.14.0

No reproduction link needed.

### Steps to reproduce
Put this inside any SSR part of your code:
```javascript
await this.$fireStorage.ref(newLogo).getDownloadURL();
```

### What is Expected?
Get the url string.

### What is actually happening?
Error:

> ReferenceError: XMLHttpRequest is not defined

Basically this happens because Firebase library is using browser's `XMLHttpRequest` and since SSR happens in node, it breaks.

My question here is how to approach this. Should we wrap firebase library with an extension of `XMLHttpRequest` for nodejs?

**Comment by JFGHT** [comment]
According to this [link](https://firebase.google.com/docs/web/setup?hl=es#namespace), firestore is not supported in node.

**Comment by JFGHT** [comment]
@lupas Shall we add something in the docs regarding the non-compatible firebase modules during SSR?

**Comment by lupas** [comment]
@JFGHT 
Put it on my ToDo list here https://github.com/nuxt-community/firebase-module/issues/298, thanks for the input!
