### ISSUE TITLE
Authorization header leads to strapi cms 401

### ISSUE THREAD

**Issue by TimoTheus27** [nuxt-community/firebase-module#292]
### Version
"@nuxtjs/firebase": "^6.1.1",
"firebase": "^7.17.2",
"nuxt": "^2.14.1",
"@nuxtjs/pwa": "^3.0.0-beta.20",

### Steps to reproduce
I'm fetching data from my strapi cms. If the firebase-auth-sw.js is running the fetch hook on my pages, where I need to fetch public data from strapi cms, fails with 401. The serviceworker sets an Authorization header for my SSR login with firebase, as explained here: https://firebase.nuxtjs.org/tutorials/ssr/

This header is then still set when I fetch the strapi cms api, which leads to 401 errors. I fixed it locally by adding the routes which use fetch the cms to ignorePaths in the firebase-auth-sw.js file but it gets overridden if I redeploy the app. 

How can I solve this issue? I was thinking to add another serviceworker wo my app, thats overrides the fetch listener for the strapi routes from the firebase-auth-sw.js, but I'm not sure if that could work.

**Comment by TimoTheus27** [comment]
fixed it by =>
`auth: {
  ssr: {
    // ...
    ignorePaths: [
      '/api/',
      // or
      /^api\//
    ]
  }
}`

**Comment by lupas** [comment]
@TimoTheus27 
Never used Strapi together with this module so I never encountered the issue yet.
I'll check it out and will probably add your solution to the docs.

Thanks for the info!

**Comment by lupas** [comment]
Added to "FAQ" in docs: https://github.com/nuxt-community/firebase-module/commit/8e437463ddf962be31b3822f98568e6902feab82

Will be released with 7.0.0 docs soon.
