### ISSUE TITLE
Various Documentation Improvements

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#298]
Collection of documentation improvements to be done. Collecting them here since old docs are already migrated in draft PR (https://github.com/nuxt-community/firebase-module/pull/291), will need to either wait or change in both places.

- [x] Mention non-compatible modules in SSR mode (https://github.com/nuxt-community/firebase-module/issues/273#issuecomment-683845877) see https://github.com/nuxt-community/firebase-module/pull/258/commits/82a8379803928558b32a3d752f8e4ec3b4a3467a
- [x] Better document difference between this.$fireFoo and this.$fireFooObj
- [x] FAQ Page with the most common questions https://github.com/nuxt-community/firebase-module/pull/258/commits/e0e52379e7ff9a5a43339ce1174491c40322ca61
- [x] (Re)add Algolia Search (not yet existing with in nuxt content docs theme..)

**Comment by JFGHT** [comment]
I'm curious. What do you plan to add regarding Algolia?

**Comment by lupas** [comment]
> I'm curious. What do you plan to add regarding Algolia?

Thinking of creating a PR for the [Nuxt Content Docs theme](https://content.nuxtjs.org/themes/docs) to implement an algolia-search option similar to what the [vuepress default theme](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search) offers.

Gotta get that into the theme first and then we could implement it here.

**Comment by JFGHT** [comment]
Ah ok, It's for the docs. I thought it was related to Firestore/Firebase since its a very common feature to expand those databases with (they are extremely limited).

**Comment by lupas** [comment]
All done and merged to dev, will be released and be live with v7.0.0's docs.
