### ISSUE TITLE
Documentation: Polyfill

### ISSUE THREAD

**Issue by JFGHT** [nuxt-community/firebase-module#307]
Would be nice to add in the tutorials section a how-to add the required Firebase Pollyfills for IE since this is always a bit tricky.

Related:
https://github.com/nuxt-community/firebase-module/issues/217
https://stackoverflow.com/questions/62308061/nuxt-firebase-ie-11-object-doesnt-support-property-or-method-values/64062207#64062207

**Comment by lupas** [comment]
@JFGHT 
Thanks for the tip, I'll check that out!

It looks like we could even integrate this into the module, so with a simple `polyfill: true` option one could turn polyfill on and off.

(might integrate this in the upcoming v7 already)

**Comment by JFGHT** [comment]
Yeah, thought about that too. The problem of that approach is that it reduces the flexibility on what to include.

**Comment by lupas** [comment]
> Yeah, thought about that too. The problem of that approach is that it reduces the flexibility on what to include.

Hmm, wee could provide two options:

```js
polyfill: true
```

or 

```js
polyfill: ['async-iterator','array-buffer']
```

**Comment by JFGHT** [comment]
So, `polyfill: true | string[]`, to cover both cases. And array of strings being the path from `@firebase/polyfill/node_modules/core-js/*PATH*`.

That'd be fine, I think.

**Comment by lupas** [comment]
Added to "FAQ" in docs:
https://github.com/nuxt-community/firebase-module/commit/8e437463ddf962be31b3822f98568e6902feab82

Decided not to implement it in the code as of now, since it is easily fixable by a plugin and imho not that often used.

Happy to reopen if at some point many people request it :)
