### ISSUE TITLE
How to Lazy-load

### ISSUE THREAD

**Issue by chadananda** [nuxt-community/firebase-module#311]
I use firebase only for authentication and database access for authenticated users. Is there any way to lazy-load to reduce my bundle size? I could not find reference to this question in the docs.

**Comment by lupas** [comment]
There is no way yet. BUT it's in the works and will be released with the next major update (v7) being released sometime in the coming weeks. https://github.com/nuxt-community/firebase-module/pull/258

Hang in there :)
