### ISSUE TITLE
new firebase.auth.RecaptchaVerifier does not work

### ISSUE THREAD

**Issue by fayazara** [nuxt-community/firebase-module#324]
### Version
@nuxtjs/firebase: 6.1.1
firebase: 7.21.1
nuxt: 2.14.5

Trying to use the phone auth and it requires us to use the Firebase recaptcha, as per the official [docs](https://firebase.google.com/docs/auth/web/phone-auth), we are to use the below syntax to initialise the Recaptcha Verifier.

```
window.recaptchaVerifier = new firebase.auth.RecaptchaVerifier('sign-in-button', {
  'size': 'invisible',
  'callback': function(response) {
    // reCAPTCHA solved, allow signInWithPhoneNumber.
    onSignInSubmit();
  }
});
```

### Steps to reproduce
1. Use the Nuxt Firebase's Authentication shortcut to initialise the above method 
```
<script>
export default {
  mounted() {
    window.recaptchaVerifier = new this.$fireAuth.RecaptchaVerifier(
      "sign-in-button",
      {
        size: "invisible",
        callback: function (response) {
          // reCAPTCHA solved, allow signInWithPhoneNumber.
          onSignInSubmit();
        },
      }
    );
  },
};
</script>
```

### What is Expected?
Recaptcha is verified

### What is actually happening?
Throws a Nuxt error `this.$fireAuth.RecaptchaVerifier is not a constructor`

![image](https://user-images.githubusercontent.com/15716057/95609865-0c63f800-0a7d-11eb-9392-91f5b58d144c.png)

**Comment by Mr-Zer0** [comment]
Bro @fayazara, have you got the solution?

**Comment by lupas** [comment]
@fayazara 
`this.$fireAuth` is the Firebase Auth instance, what you need to access RecaptchaVerifier is the module, like so `this.$fireAuthObj.RecaptchaVerifier`.

See https://firebase.nuxtjs.org/guide/usage#general-usage

Let me know if that helped.

**Comment by Mr-Zer0** [comment]
@lupas Thanks for your reply.
Actually I have tried as you said. 

```javascript
window.recaptchaVerifier = this.$fireAuthObj.RecaptchaVerifier('sign-in-button', {
      size: 'invisible',
      callback (response) {
        // eslint-disable-next-line no-undef
        onSignInSubmit()
      }
    })
```

I get this error



<img width="861" alt="Screen Shot 2020-10-20 at 21 58 09" src="https://user-images.githubusercontent.com/2142972/96608449-67200e00-131f-11eb-921b-65c99091d568.png">

**Comment by jhonyjss** [comment]
This worked for me !

```html
<button type="submit" class="btn btn-primary" id="recaptcha-container">LOGIN</button>
```

```javascript
 mounted () {
      this.appVerifier = new this.$fireModule.auth.RecaptchaVerifier('recaptcha-container', {
        'size': 'invisible',
        'callback': (response) => {
          console.log('workrs')
          // reCAPTCHA solved, allow signInWithPhoneNumber.
          // onSignInSubmit();
        }
      });
    },
  
  methods: {
    async login () {
      const loginWithNumber = await this.$fire.auth.signInWithPhoneNumber('+5511999999999',this.appVerifier)
      console.log(loginWithNumber)
    }
  },
```

**Comment by aerialsportshub** [comment]
Hi Johny,

When I'm using mounted, it gives me the below error.

![image](https://user-images.githubusercontent.com/76399271/136665067-135873bd-578c-493e-8931-f9024558cb45.png)

**Comment by jonadeline** [comment]
@aerialsportshub 
The first argument of `RecaptchaVerifier` method should be a valid HTML id (the one of your button), if not it's throwing this error.

**Comment by PRAJINPRAKASH** [comment]
how reset the recaptchaVerifier if error occurs

```
window.recaptchaVerifier.render().then(function(widgetId) {
  grecaptcha.reset(widgetId);
}
```
