### ISSUE TITLE
It looks like you're using the development build of the Firebase JS SDK.

### ISSUE THREAD

**Issue by cliffordh** [nuxt-community/firebase-module#327]
Receiving this in the browser console. Any ideas?

It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import * as firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

**Comment by cliffordh** [comment]
was using import firebase from 'firebase' instead of using this.$fireAuth as firebase nuxt registers firebase automatically

**Comment by ilyary** [comment]
thank you for hint!

I imported firestore.FieldPath like this:
import firebase from 'firebase'
const {firestore: {FieldPath}} = firebase

and got the same issue

now I use db.firestore.app.firebase_.firestore.FieldPath in inner functions. Where db = firestore.collection('some_colection'), for example
