### ISSUE TITLE
How to use Firebase Timestamp feature?

### ISSUE THREAD

**Issue by sergiocerrutti** [nuxt-community/firebase-module#335]
### Version
@nuxtjs/firebase: 6.1.0
firebase: 7.17.1
nuxt: 2.13.0

### Steps to reproduce
Try to use [Timestamp](https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp) feature this way:
`this.$fireStore.Timestamp`.

### What is Expected?
Timestamp should has a few methods inside like `now()` or `fromDate()`.

### What is actually happening?
`Timestamp` is not defined inside `this.$fireStore`, or I don't know how to access it.

**Comment by lupas** [comment]
Hi @sergiocerrutti 

There is a difference between the module `firestore` (which has .timestamp) and the initialized instance of `firestore()` (which does not).

You can access the module like so:
```js
this.$fireStoreObj.Timestamp
```

See https://firebase.nuxtjs.org/guide/usage#general-usage

Hope that helps.
