### ISSUE TITLE
Adding auth emulator support

### ISSUE THREAD

**Issue by uppergoal** [nuxt-community/firebase-module#350]
Being able to add the auth emulator port in the nuxt/firebase config object.

firebase.auth().useEmulator('http://localhost:9099/');

https://firebase.google.com/docs/emulator-suite/connect_auth#web

**Comment by lupas** [comment]
@uppergoal 
Thanks for the issue! Will try to implement this asap, will most likely find time for it next week.

**Comment by lupas** [comment]
Thanks to @alemoreau for PR https://github.com/nuxt-community/firebase-module/pull/356, this will be shipped with the upcoming v7.0.0.

Thanks guys!
