### ISSUE TITLE
[Documentation] Link issues

### ISSUE THREAD

**Issue by JFGHT** [nuxt-community/firebase-module#360]
https://github.com/nuxt-community/firebase-module/releases/tag/v7.0.0

- ~~The migration guide link is incorrect in the release docs.~~
- Also, if you go to the docs https://firebase.nuxtjs.org, you search for "Migration" and you click on "Migration guides", the link is incorrect.
- ~~In de FAQ, the Polyfills question has wrong reference link (https://github.com/nuxt-community/firebase-module/issues/292).~~

**Comment by lupas** [comment]
Thanks a lot for letting me know! Guess I should have slept more when writing the release notes ;-)

For the search links I'll have to check with Algolia DocSearch, since they are supposed to crawl the website every day but it seems like they don't update the content accordingly in this case..

**Comment by lupas** [comment]
Search also been fixed, Algolia search selectors were wrong after migration from Vuepress to Nuxt Content.
