### ISSUE TITLE
Types missing for emulator settings (auth and functions)

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-community/firebase-module#367]
### What is Expected?
TypeScript support for emulatorPort and emulatorHost settings in nuxt.config.js.

### What is actually happening?
Definitions are missing.

**Comment by lupas** [comment]
Thanks @DamianGlowala 

Just fixed this and released it with [v7.0.1](https://github.com/nuxt-community/firebase-module/releases/tag/v7.0.1)
