### ISSUE TITLE
emulator configuration

### ISSUE THREAD

**Issue by keesvanbemmel** [nuxt-community/firebase-module#375]
Hi all,

I couldn't find the answer, sorry if it was already stated somewhere clearly.

I'm looking for the best/most efficient way to add the emulatorPorts and hosts to my nuxt.config.js for development, but not for production.

I know the config part of firebase looks at children like config.development, but for the services like auth or firestore, the emulator ports are not set in that config key.

Are there any examples somewhere of a configuration for prod/dev using emulators in dev?

Thanks!

Kees.

**Comment by lupas** [comment]
Hey @keesvanbemmel 

Good point - this hasn't been documented properly! 

You can do the following:

```js
emulatorPort: process.env.NODE_ENV === 'development' ? 8080 : false
```

I'll add the info to the documentation (https://github.com/nuxt-community/firebase-module/commit/00ad15dd48153260e7d6a960c1dda99b32ca79ac), thanks for the input!

br, Pascal
