### ISSUE TITLE
Typescript Error: Type '"<<My VAPID key>>"' is not assignable to type '"<publicVapidKey>" | undefined'.

### ISSUE THREAD

**Issue by JuanJoseGonGi** [nuxt-community/firebase-module#400]
### Version
@nuxtjs/firebase: 7.1.1
firebase: 8.1.1
nuxt: 2.14.6
@nuxt/typescript-runtime: 2.0.0
@nuxt/types: 2.14.6
@nuxt/typescript-build: 2.0.3

### Steps to reproduce
1. Use nuxt typescript runtime. https://typescript.nuxtjs.org/guide/runtime
2. Change nuxt.config.js by nuxt.config.ts
3. Define the nuxt config as 
![image](https://user-images.githubusercontent.com/29153242/101098717-653da180-3591-11eb-9159-c19790e97d11.png)
and export it at the bottom
![image](https://user-images.githubusercontent.com/29153242/101098683-5525c200-3591-11eb-995c-6364f0122cfc.png)

4. Add `"types": ["@types/node", "@nuxt/types", "@nuxtjs/firebase"]` on tsconfig.json file as specified on https://firebase.nuxtjs.org/tutorials/typescript
5. Set `fcmPublicVapidKey` value to any string on `nuxt.config.ts` as shown below.
![image](https://user-images.githubusercontent.com/29153242/101098374-d2046c00-3590-11eb-909a-3141ae00081b.png)

### What is Expected?
No error

### What is actually happening?
`Type '"any vapid key"' is not assignable to type '"<publicVapidKey>" | undefined'.`
Maybe the types are wrong. The following image shows the type definition for `fcmPublicVapidKey`
![image](https://user-images.githubusercontent.com/29153242/101098523-10019000-3591-11eb-8c82-110b8dd38ccf.png)

**Comment by lupas** [comment]
Thanks a lot - you are completely right!

The fcmPublicVapidKey was in the Firebase Configuration in an earlier version and we moved it to the messaging config, but it seems we forgot to change the types accordingly.

Fixed it with [v7.1.2](https://github.com/nuxt-community/firebase-module/releases/tag/v7.1.2).

Appreciate the well documented issue - thanks a lot again!
