### ISSUE TITLE
add config option for disabling auth emulator warning

### ISSUE THREAD

**Issue by fshareef** [nuxt-community/firebase-module#415]
### Is your feature request related to a problem? Please describe.
I cannot easily develop and test my application due to the annoying emulator warning at the bottom of the page, which cannot be removed without adding custom css or using a config option. 

### Describe the solution you'd like
Implement the option to disable auth emulator warning as described in this issue ([#2773](https://github.com/firebase/firebase-tools/issues/2773)).

This has already been implemented in firebase, but this module does not support it yet. 

### Describe alternatives you've considered
Adding custom css selectors to hide the warning, which is not optimal.

### Additional context

This is what it looks like when the auth emulator is used:

![image](https://user-images.githubusercontent.com/7753335/102913894-80187d00-4490-11eb-951c-556cd93aa3ba.png)

**Comment by lupas** [comment]
Thanks for the idea, fixed and released it with [v7.2.0](https://github.com/nuxt-community/firebase-module/compare/v7.1.2...v7.2.0).

**Comment by bluequantum** [comment]
i got a same problem! how i can turn off some of emulator? i need to interact with the real data
