### ISSUE TITLE
this.$fireAuthStore is undefined in service.auth.initialize.js

### ISSUE THREAD

**Issue by abhirakshit** [nuxt-community/firebase-module#423]
Hello,

I am in the process of upgrading to v7 but I am getting this weird "this.$fireAuthStore is undefined" in the service.auth.initialize.js.

I have also tried to create a new plugin and the object passed does not seem to have $fireAuthStore initialized. 
The only way I could get it is if I add the "subscribeManually: true" field and then manually call that subscribe from the middleware where it seems to be initialized

Here is my config. Can someone point out what I am doing wrong?

```firebase: {
    config: {
      ...
    },
    onFirebaseHosting: true,
    services: {
      auth: {
        initialize: {
          onAuthStateChangedAction: 'onAuthStateChangedAction'
        }
      },
      firestore: true,
      functions: functions,
      database: true,
      storage: true,
      performance: true,
      analytics: true
    }
  }
```

Versions
@nuxt/firebase: "^7.3.0"
firebase: "8.2.1"

**Comment by lupas** [comment]
Hey @abhirakshit 

Hmm interesting, that's weird.

Could you check if a `.nuxt/firebase/service.auth.js` file is being generated in your project folder?
And if so, could you also put the following into your `nuxt.config.js` and let me know the output?

```js
  extendPlugins(plugins) {
    console.log(plugins)
    return plugins
  },
```

It would be important that the `firebase/index.js` comes before the `service.auth.initialize.js` plugin.

```js
[ 
  {
    src: '/Users/user/project/.nuxt/firebase/index.js',
    ssr: undefined,
    mode: undefined
  },
  {
    src: '/Users/user/project/.nuxt/firebase/service.auth.initialize.js',
    ssr: undefined,
    mode: undefined
  }
]
```

**Comment by abhirakshit** [comment]
Hey @lupas 

Thanks for the quick response. Here is what I found

- This file .nuxt/firebase/service.auth.js is being generated in the project folder
- Here is the output after adding the extend 
```{
    src: '/Users/abc/Projects/nuxtjs/oxhibit-admin/src/.nuxt/firebase/index.js',
    ssr: undefined,
    mode: undefined
  },
  {
    src: '/Users/abc/Projects/nuxtjs/oxhibit-admin/src/.nuxt/firebase/service.auth.initialize.js',
    ssr: undefined,
    mode: undefined
  },
```

**Comment by lupas** [comment]
@abhirakshit 

Hmm... then that's not it.
Does the error also happen if you reduce your config to the following?

```js
config: {
      ...
    },
    services: {
      auth: {
        initialize: {
          onAuthStateChangedAction: 'onAuthStateChangedAction'
        }
      },
    }
  }
```

When exactly does the error happen? During a regular `npm run dev` (= `nuxt`) serve? Target = server?
What Nuxt version are you using?

**Comment by abhirakshit** [comment]
Hey @lupas 

Thanks for pointing out the nuxt version.
The issue was happening with my nuxt version 2.0.0 but when I upgraded to the latest 2.14.12 the issue got resolved.
I guess the older version of nuxt was the issue.

Thanks for all the help!

**Comment by lupas** [comment]
@abhirakshit 
Cool stuff, glad I could help!

Have a happy new year tmrw!
