### ISSUE TITLE
Is this module compatible with vuex-class-component?

### ISSUE THREAD

**Issue by pingustar** [nuxt-community/firebase-module#429]
I am using the [vuex-class-component](https://github.com/michaelolof/vuex-class-component) for my nuxt store ... but I am not able to get the `onAuthStateChangedMutation` option in side the `nuxt.config.js` to work. 

Always getting this error: `[vuex] unknown mutation type: core/ON_AUTH_STATE_CHANGED_MUTATION`

Just wondering if I am doing something wrong or if there is just no support for this vuex class library.

**Comment by lupas** [comment]
Hey @pingustar 
Could you share your config in nuxt.config.js?

Seems like it is looking for the mutation in the `core` [vuex module](https://vuex.vuejs.org/guide/modules.html), did you put  mutation there and name it `ON_AUTH_STATE_CHANGED_MUTATION` ?

**Comment by lupas** [comment]
> Inactive for a month, closing this issue.
