### ISSUE TITLE
Firebase is already defined in the global scope.

### ISSUE THREAD

**Issue by GuasaPlay** [nuxt-community/firebase-module#432]
![1](https://user-images.githubusercontent.com/45466316/104128514-f85abb80-5335-11eb-91b2-ed224947d1ac.PNG)

This alert appears in the browser console, so is there a solution to this warning?

**Comment by lupas** [comment]
@GuasaPlay 
Do you load Firebase yourself somewhere in the app? If you use nuxt-firebase, you are not supposed to load Firebase yourself anywhere in your app.

**Comment by GuasaPlay** [comment]
Ooops. Yes it was loading firebase in the head in the nuxt.config.js file. I really hadn't noticed.
![image](https://user-images.githubusercontent.com/45466316/104131272-66f24600-5343-11eb-9626-ae43851f9472.png)

I removed it and now the warning no longer appears... Thanks for the help I am new to this 🙌

**Comment by lupas** [comment]
Glad it works now :) Happy to help!
