### ISSUE TITLE
Vuexfire does not work with the new version of @nuxtjs/firebase ^7.3.0 module

### ISSUE THREAD

**Issue by GuasaPlay** [nuxt-community/firebase-module#434]
Hi everyone! 

I started to use the vuexfire package to deploy in my project but I think with the new version of @nuxtjs/firebase the implementation with vuexfire has broken.

![image](https://user-images.githubusercontent.com/45466316/104337130-2588a480-54c3-11eb-8012-babea178eafd.png)
![image](https://user-images.githubusercontent.com/45466316/104337085-19044c00-54c3-11eb-96e2-9435573146de.png)

Any solution?

**Comment by lupas** [comment]
Hey @GuasaPlay 

Just updated the demo in [nuxt-fire-vuexfire-example](https://github.com/lupas/nuxt-fire-vuexfire-example) and it works perfectly.

Please follow the updated code there and try again. Let me know if it still does not work.

br, Pascal

**Comment by GuasaPlay** [comment]
Thanks for answering so quickly 😊 now it works.

Just one question: vuexfireMutations always have to go in the store's `index.js` when using [modules](https://nuxtjs.org/docs/2.x/directory-structure/store#modules)?
Because I get an error when adding the vuexfireMutations in a module.
![image](https://user-images.githubusercontent.com/45466316/104791944-92719800-576a-11eb-9bfc-56ab03c84fa2.png)
