### ISSUE TITLE
[BUG] Build failing when service option `auth` is Boolean (-> Fix coming soon)

### ISSUE THREAD

**Issue by aaharu** [nuxt-community/firebase-module#446]
### Version
@nuxtjs/firebase: 7.4.0
firebase: 
nuxt: 

### What is actually happening?

in `lib/plugins/services/auth.js`

```js
<% const hasOnAuthStateChangedMutation = (typeof serviceOptions.initialize.onAuthStateChangedMutation === 'string') %>
<% const hasOnAuthStateChangedAction = (typeof serviceOptions.initialize.onAuthStateChangedAction === 'string') %>
<% const hasOnAuthStateChanged = (hasOnAuthStateChangedMutation || hasOnAuthStateChangedAction) %>
<% const onIdTokenChangedMutation = (typeof serviceOptions.initialize.onIdTokenChangedMutation === 'string') %>
<% const onIdTokenChangedAction = (typeof serviceOptions.initialize.onIdTokenChangedAction === 'string') %> 
<% const hasIdTokenChanged = (onIdTokenChangedMutation || onIdTokenChangedAction) %>
```

`Cannot read property 'onAuthStateChangedMutation' of undefined`, because these lines has be put before `<% if (serviceOptions.initialize) { %>`

**Comment by lupas** [comment]
Hey @aaharu 

Can you share how you configured this in your nuxt.config.js?

**Comment by aaharu** [comment]
```js
services: {
      auth: true,
```

error occurs when `auth` is Boolean

**Comment by lupas** [comment]
Got it, will fix this asap and release a fix later today.
For now - for your case - stay on v7.3.3 and you should be fine.

Thanks for the issue, appreciate it.
