### ISSUE TITLE
logEvent() is undefind!

### ISSUE THREAD

**Issue by ehsanialireza** [nuxt-community/firebase-module#459]
i were using nuxt-firebase in my project(7.3) and everything was working fine.
but after i updated to (7.4.1), i can not use analytics.
i get this error: Cannot read property 'logEvent' of undefined

code: this.$fireAnalytics.logEvent

and i did not change enything in my code.

whats the solution?

**Comment by lupas** [comment]
This was changes way before 7.3, you should use `this.$fire.analytics`, see https://firebase.nuxtjs.org/community/migrate
