### ISSUE TITLE
How can I access firebase types?

### ISSUE THREAD

**Issue by magpiedigital** [nuxt-community/firebase-module#467]
I'm trying to create helper functions that involve firebase types

Here's an example for my backend and I'd like something similar in nuxt

```
function setDoc<T>(
  ref: FirebaseFirestore.DocumentReference,
  data: TypedWriteData<T>,
  options?: WriteOptions,
) {
  const createData = {
    dateCreated: admin.firestore.FieldValue.serverTimestamp(),
    dateUpdated: admin.firestore.FieldValue.serverTimestamp(),
    ...data,
  }

  if (options?.batch) {
    return options.batch.set(ref, createData, { merge: true })
  } else if (options?.transaction) {
    return options.transaction.set(ref, createData, { merge: true })
  } else {
    return ref.set(createData, { merge: true })
  }
}
```

However, I can't access the type FirebaseFirestore.DocumentReference because FirebaseFirestore is undefined.

I've also tried firebase.firestore.Firestore

my tsconfig types includes "@nuxtjs/firebase"

**Comment by lesharris** [comment]
You import the firebase namespace from firebase/app then it functions much the same as admin in your backend:

```import firebase from 'firebase/app'

someFunc() {
    let timestamp: firebase.firestore.Timestamp
}```
