### ISSUE TITLE
Subscrbing (listening) to TOPIC

### ISSUE THREAD

**Issue by Megachill** [nuxt-community/firebase-module#486]
Been following your documentation but I could find absolutely nothing surrounding listening in on topics. While I can connect and everything, we have deprecated direct token communication in our API and information is flowing directly through topics now since we need to be sharing certain "channels" (topics)

So simple question, is there a simple way to subscribe and listen to a topic?

Thank you

**Comment by lupas** [comment]
cosing due to inactivity
