### ISSUE TITLE
[Question] Deploying Firebase WebApp

### ISSUE THREAD

**Issue by jamesolrog** [nuxt-community/firebase-module#489]
Hi! I am looking to deploy my firebase application using firebase hosting. I was wondering whether this module has the tools necessary for this (i.e the `firebase deploy` related code)? Or will I have to install the separate firebase packages as per [this tutorial](https://dev.to/kiritchoukc/deploy-nuxt-on-firebase-4ad8)? I couldn't find anything in the docs but the module has been so useful already so I thought there might be something! Thanks in advance!

**Comment by lupas** [comment]
Hey @jamesolrog 

This module helps implementing the [Firebase JS SDK](https://firebase.google.com/docs/reference/js) to be used in a Nuxt Application.

Deployment to Firebase works via Firebase CLI which can be easily done as described in the tutorial you mentioned.
