### ISSUE TITLE
Push notifications action

### ISSUE THREAD

**Issue by MSkred** [nuxt-community/firebase-module#492]
Hi everyone,

In the documentation of firebase-module we've a key `actions` for define an action with title and url.
But this action is enabled only on the button and not on entierty of the push notification. 

Is it possible to pass and another payload for don't have action button and have an action on the entierty of the cell ?

**Comment by lupas** [comment]
Hey @MSkred 

Sorry for the late response - is this still an issue?
Have you tried injecting your code it with https://firebase.nuxtjs.org/service-options/messaging#inject ?
