### ISSUE TITLE
Can't access firebase. auth. PhoneAuthProvider

### ISSUE THREAD

**Issue by roselily8** [nuxt-community/firebase-module#506]
Hi Lupas,

I've tried to access firebase. auth. PhoneAuthProvider through both $fire.auth and $fireModule.auth. It's throwing an error. Not sure if this is a bug or a usage issue.

Thanks,

**Comment by lupas** [comment]
Hey roselily8

It should work like this:
```js
const provider = this.$fireModule.auth.PhoneAuthProvider()
```

Let me know if it wouldn't.

**Comment by roselily8** [comment]
@lupas That's what I've tried. It returns undefined.

**Comment by lupas** [comment]
Hey @roselily8 

Sorry, I forgot to add the `new`, does it work like so?

```js
const provider = new this.$fireModule.auth.PhoneAuthProvider()
```
