### ISSUE TITLE
How to use signInWithCustomToken with this module and authenticate firebase write request.

### ISSUE THREAD

**Issue by dhara15101991** [nuxt-community/firebase-module#509]
Here is my feature. My authentication is done from the server and it gives me a token. I have few tables in my firebase database so I don't require the user should log in from the firebase default authentication. Because of the securing firebase rules, I need users to be authenticated. I searched and found that using `signInWithCustomToken` I can achieve it. But I didn't found a document on how to use it. But remember my main `auth` is server-based. I only need this for the writing some data to database.  

Can anyone please guide me? Also If this is used then when I update the database is it going to pass logged in user auth so my security rule can pass the request. Here is security rule.

`allow read, write: if request.auth != null;`

**Comment by tibs245** [comment]
I think don't understand. But I can try suppose.

- You have client to send to send request read / write to firestore
- You have personalized authentication système in server

You want that a user can send read/write request to firestore directly after personnalized server connection ?

 If yes :
 - Server side : You can create token with this tutorial : https://firebase.google.com/docs/auth/admin/create-custom-tokens
 - Client side : You use this token for signIn : https://firebase.google.com/docs/auth/web/custom-auth
 
 I hope this response help you. If I have don't understand. 
 I would like more information : Maybe a draw ?
