### ISSUE TITLE
Missing or insufficient permissions when using with Firebase Firestore

### ISSUE THREAD

**Issue by dhara15101991** [nuxt-community/firebase-module#510]
### Version
@nuxtjs/firebase:  "^7.5.0"
firebase:  "^8.2.9"
nuxt: "^2.15.0"

I have followed all steps as mentioned in [this link](https://firebase.nuxtjs.org/tutorials/ssr/#firebase-auth-in-ssr-universal-mode).

But when I try to write to the database it is showing me `Missing or insufficient permissions `. My security rules are as below

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    allow read;
    allow write: if request.auth != null;
  }
}
```

It should work but not working. If I delete `if request.auth != null` then it is working so I have no idea what is wrong with it. Even I downloaded demo from git and replaced my credentials. there also is showing same error. Can anyone please guide me.

**Comment by dosstx** [comment]
It might be because your user auth object is still `null` at the time of the database write. I'm seeing the same problems on my end,

**Comment by lupas** [comment]
Hey @dhara15101991

Sorry for the late response - Is this still an issue?

**Comment by dhara15101991** [comment]
Hello @lupas Solved it
