### ISSUE TITLE
ReferenceError: $fire is not defined

### ISSUE THREAD

**Issue by NantipatSoftEn** [nuxt-community/firebase-module#514]
### Version
@nuxtjs/firebase: 
firebase: 
nuxt: 

### Problem  
this is  file nuxt.config.js

```js
  modules: [
    [
      "@nuxtjs/firebase",
      {
        config: {
          apiKey: "***************",
          authDomain: "***************",
          databaseURL: "***************",
          projectId: "***************",
          storageBucket: "***************",
          messagingSenderId: "***************",
          appId: "***************",
          measurementId: "***************"
        },
        services: {
          storage: true
        }
      }
    ]
  ],
```
I'm doing follow this document 
https://firebase.nuxtjs.org/service-options/storage/ 

```js
<script>
export default {
  data() {
    return {
      storage: $fire.storage()
    };
  }
<script>
```
I got the error  `$fire is not defined`  can you give me an example and explain please.  

Thank you.

**Comment by teomankirac** [comment]
i've this same issue. 

this.$fire.firestore.collection('posts').doc(item).get().then(snapshot => {}

what fixed it for you? 


    "@nuxtjs/firebase": "^7.6.1", is my version...

thanks!
