### ISSUE TITLE
Shouldn't we able to enable cookie secure flags for Analytics module?

### ISSUE THREAD

**Issue by looiyk** [nuxt-community/firebase-module#522]
Version
@nuxtjs/firebase: "^7.1.1"
firebase: "^8.1.1"
nuxt: "^2.15.4"

We can implement google cookies via this [method](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id) However firebase does not have this feature to enable it. 

Should it be the case or have an object to turn those on? I use a lot of the console UI and less on google analytics UI, so it would be nice to enable the cookie parameters.

```
gtag('config', 'GA_MEASUREMENT_ID', {
  'cookie_prefix': 'MyCookie',
  'cookie_domain': 'blog.example.com',
  'cookie_expires': 28 * 24 * 60 * 60  // 28 days, in seconds
});
```

**Comment by lupas** [comment]
Hey @looiyk 
This doesn't seem to have anything to do with this module. IF this is a general Firebase questions, please ask it at their Repo or on StackOverflow.

Thanks
Pascal
