### ISSUE TITLE
Add options for firebase storage emulator

### ISSUE THREAD

**Issue by ishiijp** [nuxt-community/firebase-module#525]
### Is your feature request related to a problem? Please describe.
https://github.com/firebase/firebase-tools/issues/1738#issuecomment-830490921
https://github.com/firebase/firebase-tools/releases/tag/v9.11.0

Firebase storage emulator is released, but there is no options for it.

### Describe the solution you'd like
Add options like other emulators

**Comment by tibs245** [comment]
I have proposed pull request for that : https://github.com/nuxt-community/firebase-module/pull/526

Thank you for the notification :)

**Comment by lupas** [comment]
Published with [v7.6.1](https://github.com/nuxt-community/firebase-module/releases/tag/v7.6.1)
