### ISSUE TITLE
Initialize Auth - does not work in lazy mode

### ISSUE THREAD

**Issue by andyfensham** [nuxt-community/firebase-module#538]
In the documentation at the path https://firebase.nuxtjs.org/service-options/auth under the initialize section, there is a statement saying "This does not work in lazy-mode , since auth is not initialized. If you want to use this option in lazy-mode, call the authReady() function in a separate plugin."

Can we get an example on how you would call that in a seperate plugin.  I have lazy mode set to true.

Thanks

**Comment by lupas** [comment]
There you go:
https://github.com/lupas/nuxt-firebase-demo/blob/9b7b0518c438875f52a8a9807cfe0939e80d628d/plugins/lazyMode.js
