### ISSUE TITLE
Firestore and Functions enabled breaks the application with firebase: 8.6.7

### ISSUE THREAD

**Issue by ctwhome** [nuxt-community/firebase-module#550]
### Version

@nuxtjs/firebase: 7.6.1  
firebase: 8.6.7  
nuxt: 2.15.6

### Reproduction Link

```
firebase: {
    config: {
      ...
    },
    services: {
      auth: true,
      firestore: true,
      functions: true
    
    }
```

### Steps to reproduce

Enabling firestore and function services breaks the application. Or at least I haven't been able to make it work. I tried on a new nuxt project and saw the same behavior

### What is Expected?

to have access to call functions with `this.$fireModule.functions().httpsCallable('functionName');`

### What is actually happening?

The application stops working if firestore and functions services in the Nuxtjs/firebase services object are both enabled.

this is the error in the console:

```shell
client.js?06a0:102 TypeError: e.auth.addAuthTokenListener is not a function
    at n (prebuilt-d16b955d-cdb9e87f.js?6e89:14555)
    at eval (prebuilt-d16b955d-cdb9e87f.js?6e89:14558)
    at Provider.onInit (index.esm.js?ffa6:294)
    at new t (prebuilt-d16b955d-cdb9e87f.js?6e89:14557)
    at e.t (prebuilt-d16b955d-cdb9e87f.js?6e89:14797)
    at new e (prebuilt-d16b955d-cdb9e87f.js?6e89:15373)
    at eval (index.js?c68e:69)
    at Component.eval [as instanceFactory] (index.js?c68e:66)
    at Provider.getOrInitializeService (index.esm.js?ffa6:333)
    at Provider.getImmediate (index.esm.js?ffa6:129)
```

**Comment by lupas** [comment]
Please downgrade Firebase to `"firebase": "8.6.5",` and try again, the newest v8.6.7 seemed to have introduced this bug.

I assume they will fix it in the next update.

**Comment by ctwhome** [comment]
that worked thank you very much!

**Comment by Motoralfa** [comment]
> Please downgrade Firebase to `"firebase": "8.6.5",` and try again, the newest v8.6.7 seemed to have introduced this bug.
> 
> I assume they will fix it in the next update.

Thank you so much! this help me too!

**Comment by luaz** [comment]
I am getting `session.auth is not a function` by reverting to `firebase@8.6.5`. `firebase@8.4.3` works.
