### ISSUE TITLE
Firebase Version 9.0.0 - August 25, 2021

### ISSUE THREAD

**Issue by a0m0rajab** [nuxt-community/firebase-module#571]
### Version
@nuxtjs/firebase: Latest
firebase: latest
nuxt: latest

### Steps to reproduce

- use the latest version of firebase and nuxt.

### What is Expected?

- to have the app work perfectly.

### What is actually happening?

- it's breaking without giving a direct explanation, mostly because of the latest upgrade in firebase.

**Comment by a0m0rajab** [comment]
One of the errors that I had was: 

**TypeError Cannot read property 'apps' of undefined**

The solution is to downgrade from firebase 9 to 8. 

[Release Notes](https://firebase.google.com/support/release-notes/js#version_8100_-_august_19_2021)

**Comment by JuanxCursed** [comment]
Same error here on 9.0.1: **TypeError Cannot read property 'apps' of undefined**

FirebaseModule.default is undefined even with the **injectModule** property being set to true

Downgrade did fix the issue tho, but since I need a specifig feature available at v9, any way to fix it?

**Comment by dtobi59** [comment]
Facing a similar version incompatible issues also(suspected). 

**Error:** firebase not defined. 

Anyways I was able to resolve issue by downgrading firebase verssion from v9 to  v8.6.5. works well now.

**Comment by a0m0rajab** [comment]
Firebase had a major change in the last version that's causing this issue.

I think there is a need to update the library for that.

Sent from mobile device


________________________________

**Comment by lupas** [comment]
Please see https://github.com/nuxt-community/firebase-module/issues/573
