### ISSUE TITLE
Support for Firebase Version 9 +

### ISSUE THREAD

**Issue by lupas** [nuxt-community/firebase-module#573]
## Background
With [Version 9 of the Firebase JS SDK](https://firebase.googleblog.com/2021/08/the-new-firebase-js-sdk-now-ga.html), Firebase is adopting a new module first format that is optimized for elimination of unused code. The result is a potential significant reduction of Firebase library code in JavaScript bundles with a reduction of up to 80% in some scenarios. The way the Firebase modules are imported changed completely and does not really support the way this module injects Firebase into your Nuxt app.

This module was written for the Firebase Javascript SDK **Version 8 and prior**. It is currently **not compatible** with the new Version 9 supporting tree-shaking. To make it compatible with the new version while keeping the benefits of the new version, **the module would most likely need to be re-written completely**.

### Compat Syntax
You can use [v8.0.0-beta.0](https://www.npmjs.com/package/@nuxtjs/firebase/v/8.0.0-beta.0) which supports Firebase v9+ with [compat syntax](https://firebase.google.com/docs/web/modular-upgrade#update_initialization_code).

Be aware that this is not future proof and will not work from v10 on forwards.

### New Modular Mode Syntax
If you want to use Firebase version 9 in the new modular syntax, we advice you to implement Firebase yourself as described step-by-step in the following [medium article](https://lupas.medium.com/firebase-9-beta-nuxt-js-981cf3dac910). The approach is straight-forward and not harder than using this module.

This approach allows you to use three-shaking and all the features of the new version, while staying more flexible with future changes in the SDK.

## Future of this module
It is currently unclear when, and if, this module will support modular mode (i.e. Firebase version 10+).

The module needs to become lighter, only focussing on the nuxt-specific issues at hand, while keeping the flexibility of using the benefits of the newer Firebase SDK modular mode.

I personally won't find time to re-write this module in the next few months. I might, but I can't promise. So if you are interested in working on it, let me know by creating a merge request, I would greatly appreciate it.

**Comment by productfrontenddeveloper** [comment]
Come with nuxt 3 and gear support. I hope you can update soon.

**Comment by simeon9696** [comment]
@lupas I know I'm in no position to ask this but would you consider updating the packaging to include [@firebase/compat](https://www.npmjs.com/package/@firebase/app-compat)

This would allow your users to upgrade to v9 for now. It's supposed to be a[ drop in addition](https://firebase.google.com/docs/web/modular-upgrade#update_imports_to_v9_compat): 
![image](https://user-images.githubusercontent.com/31748055/135358946-311b0409-1c45-4c22-bfe1-080f89bd80db.png)

**Comment by bkuri** [comment]
FYI I just tried forking and adding `/compat` everywhere and failed miserably. There seem to be some assumptions regarding how the code was structured in v8 which apparently changed on the new version.

Hopefully @lupas can let us know what exactly needs to be changed in order for me to submit a PR, which I would be happy to do.

**Comment by lupas** [comment]
@simeon9696 , @bkuri
Thanks for the hint with the compat mode - great idea for the time being!

I just published [v8.0.0-beta.0](https://www.npmjs.com/package/@nuxtjs/firebase/v/8.0.0-beta.0) which uses the /compat packages and seems to work very well with Firebase v9+.

I'm using it already on [nuxt-firebase-demo](https://github.com/lupas/nuxt-firebase-demo) - but haven't fully tested it.

Would be great if you could test it out if it works for you, I'll do some more tests and would publish it late on.

Thanks guys for your support!
 
 PS: For the new modular way of doing things I still think either using Firebase directly on completely re-creating this module would be the way to go, since a lot would change.

**Comment by lupas** [comment]
@bkuri 
Thanks a lot for your testing - really appreciate it! So far I haven't encountered any issues, therefore just published this in [v8.0.0](https://github.com/nuxt-community/firebase-module/releases/tag/v8.0.0).

Closing this issue in favour of https://github.com/nuxt-community/firebase-module/issues/597.
