### ISSUE TITLE
Cannot read property 'apps' of undefined

### ISSUE THREAD

**Issue by eadortsu** [nuxt-community/firebase-module#580]
### Version
@nuxtjs/firebase: ^7.6.1
firebase: ^9.0.2
nuxt: ^2.15.7

### [Reproduction Link](https://github.com/eadortsu/nuxt-fire-example)
https://github.com/eadortsu/nuxt-fire-example

### Steps to reproduce
Setting up firebase in nuxt,

### What is actually happening?

Cannot read property 'apps' of undefined
![Capture](https://user-images.githubusercontent.com/40460447/133014501-9f255444-a2e5-4bd6-b248-6f8883349ecf.JPG)

**Comment by btribouillet** [comment]
Hi, I just had the same issue this morning. 

I solved it by downgrading the version of the firebase dependency following the [config](https://github.com/lupas/nuxt-firebase-demo/blob/master/package.json) from the demo.

So there is indeed an issue, but meanwhile, you can do that.

**Comment by btribouillet** [comment]
It is actually related to this issue #573

**Comment by simeon9696** [comment]
@eadortsu did you figure out how to elimnate this error on v8 of this package?
