### ISSUE TITLE
httpsCallable error obj missing details and code always set to 'cancelled'

### ISSUE THREAD

**Issue by timdiacon** [nuxt-community/firebase-module#585]
@nuxtjs/firebase: ^7.6.1
firebase: 8
nuxt: ^2.15.7

### Steps to reproduce
When throwing a functions.https.HttpsError from a function called via httpsCallable the error object doesn't contain the details property and the code property is always set to 'cancelled' regardless of what value I put in the HttpsError constructor

### What is Expected?
error.code should contain the first property in the HttpsError constructor
error.details should contain the third property in the HttpsError constructor

### What is actually happening?
error.code contains 'cancelled'
error.details is undefined

**Comment by lupas** [comment]
This has nothing to do with the nuxt/firebase module. We simply provide a way to use the JS SDK through nuxt, we don't modify any response objects coming from Firebase.

Please raise your issue on StackOverflow or the official Firebase JS SDK issue board.
