### ISSUE TITLE
Update peer dependency for firebase@9

### ISSUE THREAD

**Issue by shu-pf** [nuxt-community/firebase-module#612]
The peer dependency in @nuxtjs/firebase is still set to firebase version 8, so please update it to 9.

### Version
@nuxtjs/firebase: 8.1.1
firebase: 9.6.2
nuxt: 2.14.6

### What is Expected?

Update peerDependencies

### What is actually happening?

peerDependencies have not been updated.

**Comment by bitpunk** [comment]
"It is currently unclear when, and if, this module will support modular syntax (i.e. Firebase version 10+)." See #597
If you want to use firebase 9 and modular syntax you can checkout @lupas [firebase 9 and nuxt.js](https://lupas.medium.com/firebase-9-beta-nuxt-js-981cf3dac910) article.

**Comment by shu-pf** [comment]
I read your link.
It says that @nuxtjs/firebase v8 uses the compat syntax of Firebase SDK v9, so
I thought, The peer dependency in the package.json of @nuxtjs/firebase v8 should be Firebase SDK v9.

**Comment by lupas** [comment]
@shu-pf is right, you can safely use v9 since we started using compat mode in [v8](https://github.com/nuxt-community/firebase-module/releases/tag/v8.0.0).

I just released [v8.2.2](https://github.com/nuxt-community/firebase-module/releases/tag/v8.2.2) fixing the peerDependency.
