### ISSUE TITLE
Nuxt 3 fresh install + @nuxtjs/firebase does not run

### ISSUE THREAD

**Issue by Youdaman** [nuxt-community/firebase-module#631]
Steps to repro:

- install Nuxt 3
- follow https://firebase.nuxtjs.org/guide/getting-started
- run

Result:

```
 ERROR  Error compiling template:  { 
...
 ERROR  Cannot restart nuxt:  serialize is not defined
...
 ERROR  [unhandledRejection] serialize is not defined
```

Works fine if you install Nuxt 2 instead of Nuxt 3 -- so is it not ready for 3 yet?

**Comment by ismail-fathi** [comment]
This module is not supported on Nuxt 3!

**Comment by lupas** [comment]
Correct, currently only working for Nuxt 2. Added a warning to the readme that it's more clear.

**Comment by rahulkumarsingh73690** [comment]
Any plan for nuxt 3 @lupas

**Comment by lupas** [comment]
@rahulkumarsingh73690 

<img width="840" alt="Screenshot 2022-09-01 at 10 14 14" src="https://user-images.githubusercontent.com/4020037/187866055-a11c2fbb-4d7a-44ee-8ab4-1a20aafc8ae8.png">

**Comment by Youdaman** [comment]
> Any plan for nuxt 3 @lupas

See https://github.com/nuxt-community/firebase-module#%EF%B8%8F-nuxt-3-not-supported-%EF%B8%8F
