### ISSUE TITLE
A cookie associated with a cross-site resource at http://firebasestorage.googleapis.com/

### ISSUE THREAD

**Issue by Suv4o** [nuxt-community/firebase-module#91]
Hello Pascal Luther,

Thank you very much for this wonderful package. I'm a big fan of it and I am really enjoying it. 

I have spoken with regards to the same issue back in early November last year. I have updated my Nuxt to 2.11.0 and I'm using yo Nuxt-Fire 3.5.5. I'm also using the latest firebase-tools 7.9.0. 

I'm getting the following warning in the browsers:

**_"A cookie associated with a cross-site resource at http://firebasestorage.googleapis.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."_**

I don't know if the warring is related to this package but I have some difficulties loading(previewing)/uploading Images and other files form Firestore on both Chrome and Mozilla. The application that I'm experiencing these issues is a web platform that we are using at my workplace everyday. 

I hope we can find some solution and fix the problem.

Thank you in advance.

**Comment by lupas** [comment]
Hi @Suv4o 

I'm glad you like nuxt-fire :)
As mentioned in https://github.com/lupas/nuxt-fire/issues/52, I don't think there is much we can do from nut-fire side at this point and this should be addressed by Firebase at some point.

One issue that might be related is this one [here](https://github.com/firebase/firebase-js-sdk/issues/2284), maybe keep track there.

I assume your application is working fine nevertheless? If so, I would say you can still largely ignore this issue for now.

Could you create a codepen/repo where I could reproduce the error? Do you know when/from what it is triggered exactly? 

Thanks

**Comment by lupas** [comment]
Close due to inactivity.
