### ISSUE TITLE
Possibility moving to NuxtCommunity

### ISSUE THREAD

**Issue by pi0** [nuxt-community/firebase-module#94]
Hi @lupas. This is an awesome project :heart: 

As advised by @pimlie would be awesome moving this project under `nuxt-community` and `@nuxtjs` umbrella making it more official. You will still have full admin and publish access and credit. Please tell me if interested so we can discuss on next steps.

**Comment by lupas** [comment]
@pi0 
As discussed in Discord - all done, nuxt-fire is now officially `@nuxtjs/firebase` and has been published as [v4.0.0](https://github.com/nuxt-community/firebase-module/releases/tag/v4.0.0) today ! <:o)

Happy to have this module to be part of the nuxt community :-)
